// Comprehensive bait, lure, and fly database for UK fishing
// Each entry is a single item that can be searched by name or alias

export interface BaitEntry {
  name: string;
  category: 'lure' | 'fly' | 'float' | 'ledger' | 'bait' | 'other';
  aliases?: string[];
}

// ============================================================
// FLIES — comprehensive UK patterns
// ============================================================
export const FLIES: BaitEntry[] = [
  // Dry flies
  { name: 'Olive Klinkhammer', category: 'fly', aliases: ['klinkhammer', 'klink', 'olive klink'] },
  { name: 'Elk Hair Caddis', category: 'fly', aliases: ['elk hair', 'caddis dry', 'sedge dry'] },
  { name: 'Adams', category: 'fly', aliases: ['adams dry'] },
  { name: 'Mayfly Dun', category: 'fly', aliases: ['mayfly', 'green drake', 'ephemera'] },
  { name: 'Mayfly Spinner', category: 'fly', aliases: ['spent mayfly', 'spent gnat'] },
  { name: 'Green Drake', category: 'fly', aliases: ['green drake mayfly'] },
  { name: 'Spent Gnat', category: 'fly', aliases: ['spent spinner'] },
  { name: 'Greenwells Glory', category: 'fly', aliases: ['greenwell', 'greenwells'] },
  { name: 'Sherry Spinner', category: 'fly', aliases: ['sherry'] },
  { name: 'Blue Winged Olive', category: 'fly', aliases: ['bwo', 'blue wing olive'] },
  { name: 'Large Olive', category: 'fly', aliases: ['large olive dun'] },
  { name: 'Hopper', category: 'fly', aliases: ['grasshopper', 'hopper fly'] },
  { name: 'Beetle', category: 'fly', aliases: ['cockchafer', 'beetle fly'] },
  { name: 'Ant', category: 'fly', aliases: ['flying ant', 'ant fly'] },
  { name: 'Crane Fly', category: 'fly', aliases: ['daddy long legs', 'crane'] },
  { name: 'Hawthorn', category: 'fly', aliases: ['hawthorn fly'] },
  { name: 'Tups Indispensable', category: 'fly', aliases: ['tups', 'tups indisp'] },
  { name: 'Black Gnat', category: 'fly', aliases: ['gnat'] },
  { name: 'Griffiths Gnat', category: 'fly', aliases: ['griffith gnat'] },
  { name: 'Ginger Quill', category: 'fly', aliases: ['ginger'] },
  { name: 'Red Quill', category: 'fly', aliases: ['red quill'] },
  { name: 'Iron Blue Dun', category: 'fly', aliases: ['iron blue'] },
  { name: 'Pale Watery', category: 'fly', aliases: ['pale watery dun'] },
  { name: 'Medium Olive', category: 'fly', aliases: ['medium olive dun'] },
  { name: 'False March Brown', category: 'fly', aliases: ['march brown'] },
  { name: 'March Brown', category: 'fly', aliases: ['march brown dun'] },
  { name: 'Turkey Brown', category: 'fly', aliases: ['turkey brown nymph'] },
  { name: 'Welmans Fancy', category: 'fly', aliases: ['welmans'] },
  { name: 'Bumble', category: 'fly', aliases: ['heather fly', 'bumble fly'] },
  { name: 'Bibio', category: 'fly', aliases: ['heather fly bibio'] },
  { name: 'Claret Bumble', category: 'fly', aliases: ['claret'] },
  { name: 'Stout Hackle', category: 'fly', aliases: ['stout'] },
  { name: 'Loch Ordie', category: 'fly', aliases: ['ordie'] },
  { name: 'Zulu', category: 'fly', aliases: ['black zulu'] },
  { name: 'Black Pennell', category: 'fly', aliases: ['pennell'] },
  { name: 'Red Tag', category: 'fly', aliases: ['red tag dry'] },
  { name: 'Coch-a-bonddhu', category: 'fly', aliases: ['coch', 'bramble fly'] },
  { name: 'Gosling', category: 'fly', aliases: ['gosling dry'] },
  { name: 'Sedge', category: 'fly', aliases: ['caddis dry', 'sedge dry'] },
  { name: 'God Sedge', category: 'fly', aliases: ['god sedge caddis'] },
  { name: 'Cinnamon Sedge', category: 'fly', aliases: ['cinnamon caddis'] },
  { name: 'Grouse Wing', category: 'fly', aliases: ['grouse and claret'] },
  { name: 'Silver Sedge', category: 'fly', aliases: ['silver sedge caddis'] },
  { name: 'Pheasant Tail Dry', category: 'fly', aliases: ['pt dry'] },

  // Nymphs
  { name: 'Pheasant Tail Nymph', category: 'fly', aliases: ['ptn', 'pheasant tail', 'pt nymph'] },
  { name: 'Gold Ribbed Hares Ear', category: 'fly', aliases: ['grhe', 'hares ear', 'gold ribbed'] },
  { name: 'Hares Ear', category: 'fly', aliases: ['hares ear nymph'] },
  { name: 'Prince Nymph', category: 'fly', aliases: ['prince'] },
  { name: 'Copper John', category: 'fly', aliases: ['copper john nymph'] },
  { name: 'Zebra Midge', category: 'fly', aliases: ['zebra midge nymph'] },
  { name: 'Olive Nymph', category: 'fly', aliases: ['olive nymph'] },
  { name: 'Stonefly Nymph', category: 'fly', aliases: ['stonefly'] },
  { name: 'Cased Caddis', category: 'fly', aliases: ['cased caddis nymph'] },
  { name: 'Rhyacophila', category: 'fly', aliases: ['rhyacophila nymph', 'free living caddis'] },
  { name: 'Buzzer', category: 'fly', aliases: ['chironomid', 'midge pupa', 'buzzer nymph'] },
  { name: 'Bloodworm', category: 'fly', aliases: ['bloodworm nymph', 'red midge larva'] },
  { name: 'Jig Nymph', category: 'fly', aliases: ['jig', 'euro nymph'] },
  { name: 'Perdigon', category: 'fly', aliases: ['perdigon nymph', 'spanish nymph'] },
  { name: 'Frenchie', category: 'fly', aliases: ['french nymph'] },
  { name: 'Squirmy Wormy', category: 'fly', aliases: ['squirmie', 'squirmy'] },
  { name: 'San Juan Worm', category: 'fly', aliases: ['san juan', 'worm fly'] },
  { name: 'Epoxy Buzzer', category: 'fly', aliases: ['epoxy midge'] },
  { name: 'Cormorant Nymph', category: 'fly', aliases: ['cormorant'] },
  { name: 'Diawl Bach', category: 'fly', aliases: ['diawl', 'peeping diawl bach', 'diawl bach flashback'] },
  { name: 'Cats Whisker', category: 'fly', aliases: ['cat whisker', 'cats whiskers', 'mini cat', 'flash cat'] },
  { name: 'Blob', category: 'fly', aliases: ['blob fly', 'orange blob', 'tequila blob'] },
  { name: 'Damsel Nymph', category: 'fly', aliases: ['damsel', 'damselfly'] },
  { name: 'Montana Nymph', category: 'fly', aliases: ['montana'] },
  { name: 'Cress Bug', category: 'fly', aliases: ['cress beetle'] },
  { name: 'Corixa', category: 'fly', aliases: ['water boatman'] },
  { name: 'Shrimp Fly', category: 'fly', aliases: ['freshwater shrimp fly'] },
  { name: 'Olive Buzzer', category: 'fly', aliases: ['olive midge'] },
  { name: 'Black Buzzer', category: 'fly', aliases: ['black midge pupa'] },
  { name: 'Red Buzzer', category: 'fly', aliases: ['red midge pupa'] },
  { name: 'Ally Buzzer', category: 'fly', aliases: ['allys buzzer'] },
  { name: 'Sparkler Buzzer', category: 'fly', aliases: ['sparkler'] },
  { name: 'Squirmy Bug', category: 'fly', aliases: ['squirmy bug nymph'] },

  // Wet flies
  { name: 'Partridge & Orange', category: 'fly', aliases: ['partridge orange', 'partridge and orange'] },
  { name: 'Partridge & Yellow', category: 'fly', aliases: ['partridge yellow'] },
  { name: 'Snipe & Purple', category: 'fly', aliases: ['snipe purple', 'snipe and purple'] },
  { name: 'Waterhen Bloa', category: 'fly', aliases: ['waterhen', 'bloa'] },
  { name: 'Kingfisher Butcher', category: 'fly', aliases: ['butcher', 'kingfisher'] },
  { name: 'Dunkeld', category: 'fly', aliases: ['dunkeld wet'] },
  { name: 'Peter Ross', category: 'fly', aliases: ['peter ross wet'] },
  { name: 'Teal Blue & Silver', category: 'fly', aliases: ['teal blue silver'] },
  { name: 'Black Zulu Wet', category: 'fly', aliases: ['zulu wet'] },
  { name: 'Connemara Black', category: 'fly', aliases: ['connemara'] },
  { name: 'Claret Bumble Wet', category: 'fly', aliases: ['claret bumble wet'] },
  { name: 'Invicta', category: 'fly', aliases: ['invicta wet'] },
  { name: 'Mallard & Claret', category: 'fly', aliases: ['mallard claret'] },
  { name: 'March Brown Wet', category: 'fly', aliases: ['march brown wet fly'] },
  { name: 'Soft Hackle', category: 'fly', aliases: ['spider', 'north country spider', 'soft hackle fly'] },
  { name: 'Pheasant Tail Spider', category: 'fly', aliases: ['pt spider'] },
  { name: 'Snipe Bloa', category: 'fly', aliases: ['snipe bloa spider'] },
  { name: 'Partridge Spider', category: 'fly', aliases: ['partridge soft hackle'] },
  { name: 'Starling & Herl', category: 'fly', aliases: ['starling herl'] },
  { name: 'Grouse & Clove', category: 'fly', aliases: ['grouse clove'] },
  { name: 'Dotterel & Yellow', category: 'fly', aliases: ['dotterel'] },
  { name: 'Woodcock & Yellow', category: 'fly', aliases: ['woodcock'] },

  // Streamers & lures (fly)
  { name: 'Woolly Bugger', category: 'fly', aliases: ['woolly', 'bugger'] },
  { name: 'Muddler Minnow', category: 'fly', aliases: ['muddler'] },
  { name: 'Clouser Minnow', category: 'fly', aliases: ['clouser'] },
  { name: 'Deceiver', category: 'fly', aliases: ['lefty deceiver', 'deceiver fly'] },
  { name: 'Sculpin', category: 'fly', aliases: ['sculpin fly'] },
  { name: 'Zonker', category: 'fly', aliases: ['rabbit zonker', 'zonker fly'] },
  { name: 'Mickey Finn', category: 'fly', aliases: ['mickey finn streamer'] },
  { name: 'Black Ghost', category: 'fly', aliases: ['black ghost streamer'] },
  { name: 'Sparkler', category: 'fly', aliases: ['sparkler lure'] },
  { name: 'Sunras', category: 'fly', aliases: ['sunras lure'] },
  { name: 'Dancer', category: 'fly', aliases: ['dancer lure', 'sunra dancer'] },
  { name: 'Viva', category: 'fly', aliases: ['viva lure', 'black viva'] },
  { name: 'Tadpole', category: 'fly', aliases: ['tadpole fly', 'tadpole lure'] },
  { name: 'Minkie', category: 'fly', aliases: ['minkie lure', 'minkie streamer'] },
  { name: 'Cat Booby', category: 'fly', aliases: ['booby cat', 'cats whisker booby'] },
  { name: 'Booby', category: 'fly', aliases: ['booby fly', 'booby lure'] },
  { name: 'Cormorant Booby', category: 'fly', aliases: ['booby cormorant'] },
  { name: 'Cormorant Minkie', category: 'fly', aliases: ['cormorant minkie lure'] },
  { name: 'Olive Buzzard', category: 'fly', aliases: ['buzzard', 'olive buzzard'] },
  { name: 'Black Buzzard', category: 'fly', aliases: ['black buzzard lure'] },
  { name: 'Dahlberg Diver', category: 'fly', aliases: ['dahlberg'] },
  { name: 'Gurgler', category: 'fly', aliases: ['gurgler fly'] },
  { name: 'Foam Popper', category: 'fly', aliases: ['popper fly', 'foam popper fly'] },
  { name: 'Egg Fly', category: 'fly', aliases: ['egg', 'glow bug', 'beadhead egg'] },
  { name: 'Glo Bug', category: 'fly', aliases: ['glow bug fly'] },
  { name: 'Salmon Egg', category: 'fly', aliases: ['salmon egg fly'] },

  // Salmon flies
  { name: 'Allys Shrimp', category: 'fly', aliases: ['allys', 'ally shrimp'] },
  { name: 'T Cascade', category: 'fly', aliases: ['cascade', 'tcascade'] },
  { name: 'Willie Gunn', category: 'fly', aliases: ['willie gunn salmon'] },
  { name: 'Garry Dog', category: 'fly', aliases: ['garry'] },
  { name: 'Sunray Shadow', category: 'fly', aliases: ['sunray'] },
  { name: 'Silver Stoat', category: 'fly', aliases: ['stoat'] },
  { name: 'Hairy Mary', category: 'fly', aliases: ['hairy mary salmon'] },
  { name: 'Blue Charm', category: 'fly', aliases: ['blue charm salmon'] },
  { name: 'Park Shrimp', category: 'fly', aliases: ['park'] },
  { name: 'Gold Bodied Willie Gunn', category: 'fly', aliases: ['gold willie gunn'] },
  { name: 'Francis', category: 'fly', aliases: ['francis salmon fly'] },
  { name: 'Monkey', category: 'fly', aliases: ['monkey fly', 'snaelda'] },
  { name: 'Snaelda', category: 'fly', aliases: ['snaelda salmon'] },
  { name: 'Temple Dog', category: 'fly', aliases: ['temple dog salmon'] },
  { name: 'Flamethrower', category: 'fly', aliases: ['flamethrower salmon'] },
  { name: 'Yellow Flying Scamp', category: 'fly', aliases: ['flying scamp'] },
  { name: 'Crathie Fly', category: 'fly', aliases: ['crathie'] },
  { name: 'Garry Dog Tube', category: 'fly', aliases: ['garry dog tube fly'] },
  { name: 'Micro Tube', category: 'fly', aliases: ['micro tube fly'] },
  { name: 'Cone Head', category: 'fly', aliases: ['conehead salmon'] },

  // Sea trout flies
  { name: 'Bibio Sea Trout', category: 'fly', aliases: ['bibio sea trout'] },
  { name: 'Butcher Sea Trout', category: 'fly', aliases: ['butcher sea trout'] },
  { name: 'Medicine', category: 'fly', aliases: ['medicine fly', 'alexandra'] },
  { name: 'Teal & Silver', category: 'fly', aliases: ['teal silver sea trout'] },
  { name: 'Muddler Sea Trout', category: 'fly', aliases: ['muddler sea trout'] },

  // Stillwater / reservoir patterns
  { name: 'Apps Bloodworm', category: 'fly', aliases: ['apps bloodworm', 'apps'] },
  { name: 'FAB', category: 'fly', aliases: ['foam arsed blob', 'fab fly'] },
  { name: 'Fritz Buzzer', category: 'fly', aliases: ['fritz', 'fritz midge'] },
  { name: 'UV Olive', category: 'fly', aliases: ['uv olive nymph'] },
  { name: 'Hot Head Damsel', category: 'fly', aliases: ['hot head damsel'] },
  { name: 'Jiggy Bugger', category: 'fly', aliases: ['jiggy'] },
  { name: 'Dancing Damsel', category: 'fly', aliases: ['dancing damsel fly'] },
  { name: 'Mega Muddler', category: 'fly', aliases: ['mega muddler'] },
  { name: 'Humungus', category: 'fly', aliases: ['humungus lure'] },
  { name: 'Killer Shrimp', category: 'fly', aliases: ['killer shrimp fly'] },
  { name: 'Orange Blob', category: 'fly', aliases: ['orange blob lure'] },
  { name: 'Tequila Blob', category: 'fly', aliases: ['tequila'] },
  { name: 'Estaz Egg', category: 'fly', aliases: ['estaz'] },
  { name: 'Squirmy Worm', category: 'fly', aliases: ['squirmy worm fly'] },
  { name: 'Snake Fly', category: 'fly', aliases: ['snake', 'snake fly lure'] },
  { name: 'Wiggle Tail', category: 'fly', aliases: ['wiggle tail fly'] },

  // === Additional stillwater / reservoir patterns ===
  { name: 'Ace of Spades', category: 'fly', aliases: ['ace of spades lure', 'ace fly'] },
  { name: 'Alexandra', category: 'fly', aliases: ['alexandra lure'] },
  { name: 'Baby Doll', category: 'fly', aliases: ['baby doll fly'] },
  { name: 'Beadhead Buzzer', category: 'fly', aliases: ['beadhead midge', 'bh buzzer'] },
  { name: 'Black & Green Fritz', category: 'fly', aliases: ['black green fritz', 'black fritz'] },
  { name: 'Black & Peacock Spider', category: 'fly', aliases: ['black peacock spider'] },
  { name: 'Black Tadpole', category: 'fly', aliases: ['black tadpole lure'] },
  { name: 'Bloodworm Buzzer', category: 'fly', aliases: ['bloodworm midge', 'red buzzer'] },
  { name: 'Blue Flash Damsel', category: 'fly', aliases: ['blue flash damsel nymph'] },
  { name: 'Booby Nymph', category: 'fly', aliases: ['booby nymph'] },
  { name: 'Bramble Fly', category: 'fly', aliases: ['bramble'] },
  { name: 'Brassie', category: 'fly', aliases: ['brassie nymph'] },
  { name: 'Bung Fly', category: 'fly', aliases: ['bung', 'indicator fly', 'sight bob'] },
  { name: 'Cats Whisker Booby', category: 'fly', aliases: ['cat booby', 'cats whisker booby'] },
  { name: 'Cats Whisker Fritz', category: 'fly', aliases: ['cat fritz', 'whisker fritz'] },
  { name: 'CDC & Elk', category: 'fly', aliases: ['cdc elk', 'cdc and elk'] },
  { name: 'CDC Emerger', category: 'fly', aliases: ['cdc emerger fly'] },
  { name: 'Chew Gum', category: 'fly', aliases: ['chew gum fly'] },
  { name: 'Chironomid Pupa', category: 'fly', aliases: ['chironomid pupa fly'] },
  { name: 'Christmas Tree', category: 'fly', aliases: ['christmas tree lure'] },
  { name: 'Cormorant & Blob', category: 'fly', aliases: ['cormorant blob'] },
  { name: 'Cormorant Pupa', category: 'fly', aliases: ['cormorant pupa'] },
  { name: 'Cruncher', category: 'fly', aliases: ['cruncher nymph'] },
  { name: 'Dabbler', category: 'fly', aliases: ['dabbler fly', 'olive dabbler'] },
  { name: 'Dancing Queen', category: 'fly', aliases: ['dancing queen lure'] },
  { name: 'Detached Body Mayfly', category: 'fly', aliases: ['detached mayfly', 'detached body'] },
  { name: 'DHE', category: 'fly', aliases: ['deer hair emerger', 'dhe fly'] },
  { name: 'Diawl Bach Flashback', category: 'fly', aliases: ['diawl bach fb', 'flashback diawl'] },
  { name: 'Disco Buzzer', category: 'fly', aliases: ['disco midge'] },
  { name: 'Dog Nobbler', category: 'fly', aliases: ['dog nobbler lure'] },
  { name: 'Dribble Bug', category: 'fly', aliases: ['dribble bug fly'] },
  { name: 'Dry Buzzer', category: 'fly', aliases: ['dry midge', 'buzzer dry'] },
  { name: 'Duckling', category: 'fly', aliases: ['duckling fly'] },
  { name: 'Emerger Caddis', category: 'fly', aliases: ['caddis emerger'] },
  { name: 'Ethel Wing', category: 'fly', aliases: ['ethel wing fly'] },
  { name: 'FAB Blob', category: 'fly', aliases: ['foam arsed blob'] },
  { name: 'Fiery Brown', category: 'fly', aliases: ['fiery brown sedge'] },
  { name: 'Flashback Pheasant Tail', category: 'fly', aliases: ['flashback ptn', 'fb ptn'] },
  { name: 'Flashback Hares Ear', category: 'fly', aliases: ['flashback grhe', 'fb grhe'] },
  { name: 'Flexi Floss Buzzer', category: 'fly', aliases: ['flexi floss midge'] },
  { name: 'Floss Buzzer', category: 'fly', aliases: ['floss midge'] },
  { name: 'Foam Beetle', category: 'fly', aliases: ['foam beetle dry'] },
  { name: 'Foam Hopper', category: 'fly', aliases: ['foam grasshopper'] },
  { name: 'Glass Buzzer', category: 'fly', aliases: ['glass midge', 'glass buzzer'] },
  { name: 'Gold Bead Hares Ear', category: 'fly', aliases: ['gbhe', 'gold bead grhe', 'beadhead hares ear'] },
  { name: 'Gold Bead Pheasant Tail', category: 'fly', aliases: ['gb ptn', 'gold bead ptn', 'beadhead ptn'] },
  { name: 'Gold Ribbed Pheasant Tail', category: 'fly', aliases: ['gr ptn'] },
  { name: 'Green & Black Fritz', category: 'fly', aliases: ['green black fritz'] },
  { name: 'Green Blob', category: 'fly', aliases: ['green blob lure'] },
  { name: 'Green Damsel', category: 'fly', aliases: ['green damsel nymph'] },
  { name: 'Green Tail', category: 'fly', aliases: ['green tail lure'] },
  { name: 'Grey Duster', category: 'fly', aliases: ['grey duster dry'] },
  { name: 'Grip Buzzer', category: 'fly', aliases: ['grip midge'] },
  { name: 'Half Hog', category: 'fly', aliases: ['half hog dry'] },
  { name: 'Hares Ear Flashback', category: 'fly', aliases: ['hares ear fb'] },
  { name: 'Hatch Buzzer', category: 'fly', aliases: ['hatch midge'] },
  { name: 'Hot Spot Blob', category: 'fly', aliases: ['hot spot blob lure'] },
  { name: 'Hot Spot Diawl Bach', category: 'fly', aliases: ['hot spot diawl'] },
  { name: 'Hot Spot Pheasant Tail', category: 'fly', aliases: ['hot spot ptn'] },
  { name: 'Humpy', category: 'fly', aliases: ['humpy dry', 'elk hair humpy'] },
  { name: 'Jig Head Buzzer', category: 'fly', aliases: ['jig buzzer'] },
  { name: 'Jig Head Diawl Bach', category: 'fly', aliases: ['jig diawl bach'] },
  { name: 'Jig Head Pheasant Tail', category: 'fly', aliases: ['jig ptn'] },
  { name: 'John Storey', category: 'fly', aliases: ['john storey dry'] },
  { name: 'Jungle Dragon', category: 'fly', aliases: ['jungle dragon lure'] },
  { name: 'Klinkhammer Special', category: 'fly', aliases: ['klinkhammer special'] },
  { name: 'Ladi Diawl', category: 'fly', aliases: ['ladi diawl bach'] },
  { name: 'Lake Olive', category: 'fly', aliases: ['lake olive dry'] },
  { name: 'Lawn Mower', category: 'fly', aliases: ['lawn mower lure'] },
  { name: 'Lazy Susan', category: 'fly', aliases: ['lazy susan lure'] },
  { name: 'Lennies Minkie', category: 'fly', aliases: ['lennies minkie lure'] },
  { name: 'Mackerel Minkie', category: 'fly', aliases: ['mackerel minkie lure'] },
  { name: 'Maggot Fly', category: 'fly', aliases: ['maggot fly pattern', 'imitation maggot'] },
  { name: 'Mallard & Claret Wet', category: 'fly', aliases: ['mallard claret wet'] },
  { name: 'Marabou Minkie', category: 'fly', aliases: ['marabou minkie'] },
  { name: 'Minkie Booby', category: 'fly', aliases: ['minkie booby lure'] },
  { name: 'Minkie Bugger', category: 'fly', aliases: ['minkie bugger'] },
  { name: 'Montana Gold', category: 'fly', aliases: ['montana gold nymph'] },
  { name: 'Moorhen', category: 'fly', aliases: ['moorhen fly'] },
  { name: 'Muddler Booby', category: 'fly', aliases: ['muddler booby'] },
  { name: 'Nemo', category: 'fly', aliases: ['nemo lure'] },
  { name: 'Nymph & Bung', category: 'fly', aliases: ['nymph and bung'] },
  { name: 'Olive Damsel', category: 'fly', aliases: ['olive damsel nymph'] },
  { name: 'Olive Fritz', category: 'fly', aliases: ['olive fritz lure'] },
  { name: 'Olive Snake', category: 'fly', aliases: ['olive snake fly'] },
  { name: 'Orange Booby', category: 'fly', aliases: ['orange booby lure'] },
  { name: 'Orange Fritz', category: 'fly', aliases: ['orange fritz lure'] },
  { name: 'Orange Minkie', category: 'fly', aliases: ['orange minkie lure'] },
  { name: 'Oyster Cutter', category: 'fly', aliases: ['oyster cutter fly'] },
  { name: 'Pheasant Tail & Hares Ear', category: 'fly', aliases: ['pt and grhe'] },
  { name: 'Pheasant Tail Buzzer', category: 'fly', aliases: ['pt buzzer'] },
  { name: 'Pheasant Tail Cruncher', category: 'fly', aliases: ['pt cruncher'] },
  { name: 'Pink Blob', category: 'fly', aliases: ['pink blob lure'] },
  { name: 'Pink Booby', category: 'fly', aliases: ['pink booby lure'] },
  { name: 'Pink Minkie', category: 'fly', aliases: ['pink minkie lure'] },
  { name: 'Pink Tailed Blob', category: 'fly', aliases: ['pink tailed blob'] },
  { name: 'Popper Hopper', category: 'fly', aliases: ['popper hopper dry'] },
  { name: 'Pupa Fly', category: 'fly', aliases: ['pupa', 'sedge pupa'] },
  { name: 'Rabbit Minkie', category: 'fly', aliases: ['rabbit minkie lure'] },
  { name: 'Rainbow Warrior', category: 'fly', aliases: ['rainbow warrior nymph'] },
  { name: 'Red Buzzer', category: 'fly', aliases: ['red buzzer midge'] },
  { name: 'Red Diawl Bach', category: 'fly', aliases: ['red diawl'] },
  { name: 'Red Flash Damsel', category: 'fly', aliases: ['red flash damsel'] },
  { name: 'Red Holographic Booby', category: 'fly', aliases: ['red holographic booby'] },
  { name: 'Red Tailed Dancer', category: 'fly', aliases: ['red tailed dancer'] },
  { name: 'Roger Baker', category: 'fly', aliases: ['roger baker fly'] },
  { name: 'Sedge Pupa', category: 'fly', aliases: ['caddis pupa', 'sedge pupa fly'] },
  { name: 'Silver Dabbler', category: 'fly', aliases: ['silver dabbler fly'] },
  { name: 'Silver Invicta', category: 'fly', aliases: ['silver invicta wet'] },
  { name: 'Slim Buzzer', category: 'fly', aliases: ['slim buzzer midge'] },
  { name: 'Snappy Dancer', category: 'fly', aliases: ['snappy dancer lure'] },
  { name: 'Spearhead Minkie', category: 'fly', aliases: ['spearhead minkie'] },
  { name: 'Sparkler Booby', category: 'fly', aliases: ['sparkler booby lure'] },
  { name: 'Spent Caddis', category: 'fly', aliases: ['spent sedge'] },
  { name: 'Spent Mayfly', category: 'fly', aliases: ['spent mayfly dry'] },
  { name: 'Spider Minkie', category: 'fly', aliases: ['spider minkie lure'] },
  { name: 'Squirmy Worm Red', category: 'fly', aliases: ['red squirmy worm'] },
  { name: 'Squirmy Worm Pink', category: 'fly', aliases: ['pink squirmy worm'] },
  { name: 'Stickleback Fly', category: 'fly', aliases: ['stickleback', 'stickleback imitation'] },
  { name: 'Stonefly Dry', category: 'fly', aliases: ['stonefly dry fly'] },
  { name: 'Suspender Buzzer', category: 'fly', aliases: ['suspender midge'] },
  { name: 'Teal Blue & Silver Wet', category: 'fly', aliases: ['teal blue silver wet'] },
  { name: 'Tequila Blob Booby', category: 'fly', aliases: ['tequila booby'] },
  { name: 'UV Blob', category: 'fly', aliases: ['uv blob lure'] },
  { name: 'UV Buzzer', category: 'fly', aliases: ['uv buzzer midge'] },
  { name: 'UV Damsel', category: 'fly', aliases: ['uv damsel nymph'] },
  { name: 'UV Fritz Booby', category: 'fly', aliases: ['uv fritz booby'] },
  { name: 'UV Minkie', category: 'fly', aliases: ['uv minkie lure'] },
  { name: 'Viva Booby', category: 'fly', aliases: ['viva booby lure'] },
  { name: 'Viva Minkie', category: 'fly', aliases: ['viva minkie lure'] },
  { name: 'White Booby', category: 'fly', aliases: ['white booby lure'] },
  { name: 'White Minkie', category: 'fly', aliases: ['white minkie lure'] },
  { name: 'White Snake', category: 'fly', aliases: ['white snake fly'] },
  { name: 'Wiggle Snake', category: 'fly', aliases: ['wiggle snake fly'] },
  { name: 'Woolly Bugger Beadhead', category: 'fly', aliases: ['beadhead bugger', 'bh bugger'] },
  { name: 'Woolly Bugger Black', category: 'fly', aliases: ['black woolly bugger'] },
  { name: 'Woolly Bugger Olive', category: 'fly', aliases: ['olive woolly bugger'] },
  { name: 'Woolly Bugger White', category: 'fly', aliases: ['white woolly bugger'] },
  { name: 'Yellow Dancer', category: 'fly', aliases: ['yellow dancer lure'] },
  { name: 'Yellow Owl', category: 'fly', aliases: ['yellow owl fly'] },
  { name: 'Zonker Minkie', category: 'fly', aliases: ['zonker minkie lure'] },

  // === Additional river / stream dry flies ===
  { name: 'Baetis Nymph', category: 'fly', aliases: ['baetis', 'baetis nymph'] },
  { name: 'Black & Peacock Dry', category: 'fly', aliases: ['black peacock dry'] },
  { name: 'Black Gnat Dry', category: 'fly', aliases: ['black gnat dry'] },
  { name: 'Blue Dun', category: 'fly', aliases: ['blue dun dry'] },
  { name: 'Blue Quill', category: 'fly', aliases: ['blue quill dry'] },
  { name: 'Brown Caddis', category: 'fly', aliases: ['brown caddis dry'] },
  { name: 'Caddis Dry', category: 'fly', aliases: ['caddis dry fly', 'adult caddis'] },
  { name: 'Cdc Mayfly', category: 'fly', aliases: ['cdc mayfly dry'] },
  { name: 'Cdc Olive', category: 'fly', aliases: ['cdc olive dry'] },
  { name: 'Cdc Sedge', category: 'fly', aliases: ['cdc sedge dry', 'cdc caddis'] },
  { name: 'Cinnamon Sedge Dry', category: 'fly', aliases: ['cinnamon sedge dry'] },
  { name: 'Claret Bumble Dry', category: 'fly', aliases: ['claret bumble dry fly'] },
  { name: 'Comparadun', category: 'fly', aliases: ['comparadun dry'] },
  { name: 'Cul de Canard', category: 'fly', aliases: ['cdc', 'cdc fly', 'cul de canard dry'] },
  { name: 'Deer Hair Caddis', category: 'fly', aliases: ['deer hair sedge', 'deer caddis'] },
  { name: 'Deer Hair Sedge', category: 'fly', aliases: ['deer hair caddis dry'] },
  { name: 'Dun Fly', category: 'fly', aliases: ['dun', 'dun dry fly'] },
  { name: 'Elk Hair Caddis Olive', category: 'fly', aliases: ['elk hair caddis olive'] },
  { name: 'Emerger Mayfly', category: 'fly', aliases: ['mayfly emerger'] },
  { name: 'Emerger Olive', category: 'fly', aliases: ['olive emerger', 'bwo emerger'] },
  { name: 'F Fly', category: 'fly', aliases: ['f fly', 'f-fly cdc'] },
  { name: 'Floating Nymph', category: 'fly', aliases: ['floating nymph dry'] },
  { name: 'Goddard Caddis', category: 'fly', aliases: ['goddard sedge', 'goddard caddis dry'] },
  { name: 'Gold Ribbed Hares Ear Dry', category: 'fly', aliases: ['grhe dry'] },
  { name: 'Grannom', category: 'fly', aliases: ['grannom dry', 'grannom caddis'] },
  { name: 'Grannom Emerger', category: 'fly', aliases: ['grannom emerger'] },
  { name: 'Green Sedge', category: 'fly', aliases: ['green sedge dry'] },
  { name: 'Grey Duster Dry', category: 'fly', aliases: ['grey duster'] },
  { name: 'Grouse & Green', category: 'fly', aliases: ['grouse green'] },
  { name: 'Hares Ear Dry', category: 'fly', aliases: ['hares ear dry fly'] },
  { name: 'Hendrickson', category: 'fly', aliases: ['hendrickson dry'] },
  { name: 'Hoppers Dry', category: 'fly', aliases: ['hopper dry fly'] },
  { name: 'Jenny Spinner', category: 'fly', aliases: ['jenny spinner dry'] },
  { name: 'Klinkhammer Olive', category: 'fly', aliases: ['olive klinkhammer emerger'] },
  { name: 'Klinkhammer Black', category: 'fly', aliases: ['black klinkhammer'] },
  { name: 'Large Dark Olive', category: 'fly', aliases: ['large dark olive dry', 'ldo'] },
  { name: 'Large Reed Sedge', category: 'fly', aliases: ['large reed sedge dry'] },
  { name: 'LDO Emerger', category: 'fly', aliases: ['large dark olive emerger'] },
  { name: 'Loop Wing Emerger', category: 'fly', aliases: ['loop wing', 'loop wing olive'] },
  { name: 'Mayfly Emerger', category: 'fly', aliases: ['mayfly emerger fly'] },
  { name: 'Midge Dry', category: 'fly', aliases: ['midge dry fly'] },
  { name: 'Olive Para', category: 'fly', aliases: ['olive parachute', 'olive para dry'] },
  { name: 'Parachute Adams', category: 'fly', aliases: ['para adams', 'parachute adams'] },
  { name: 'Parachute BWO', category: 'fly', aliases: ['para bwo', 'parachute bwo'] },
  { name: 'Parachute Mayfly', category: 'fly', aliases: ['para mayfly', 'parachute mayfly'] },
  { name: 'Parachute Olive', category: 'fly', aliases: ['para olive', 'parachute olive'] },
  { name: 'Peacock Quill', category: 'fly', aliases: ['peacock quill dry'] },
  { name: 'Quill Dry', category: 'fly', aliases: ['quill dry fly'] },
  { name: 'Red Spinner', category: 'fly', aliases: ['red spinner dry'] },
  { name: 'Rusty Spinner', category: 'fly', aliases: ['rusty spinner dry'] },
  { name: 'Sedge Dry', category: 'fly', aliases: ['sedge dry fly'] },
  { name: 'Sparkle Dun', category: 'fly', aliases: ['sparkle dun dry'] },
  { name: 'Spent Caddis Dry', category: 'fly', aliases: ['spent caddis dry fly'] },
  { name: 'Spent Olive', category: 'fly', aliases: ['spent olive dry'] },
  { name: 'Tent Wing Caddis', category: 'fly', aliases: ['tent wing caddis dry'] },
  { name: 'Tom Bean', category: 'fly', aliases: ['tom bean dry'] },
  { name: 'Tups Indispensable Dry', category: 'fly', aliases: ['tups dry'] },
  { name: 'Turkey Brown Dry', category: 'fly', aliases: ['turkey brown dry fly'] },
  { name: 'Wickhams Fancy', category: 'fly', aliases: ['wickhams', 'wickham fancy'] },
  { name: 'Wulff', category: 'fly', aliases: ['wulff dry', 'royal wulff'] },
  { name: 'X Caddis', category: 'fly', aliases: ['x caddis dry'] },
  { name: 'Yellow May', category: 'fly', aliases: ['yellow may dun', 'potamanthus'] },
  { name: 'Yellow Sally', category: 'fly', aliases: ['yellow sally dry', 'stonefly yellow sally'] },

  // === Additional river / stream nymphs & wet flies ===
  { name: 'Beadhead Pheasant Tail', category: 'fly', aliases: ['bh ptn', 'beadhead pheasant tail'] },
  { name: 'Beadhead Prince', category: 'fly', aliases: ['bh prince', 'beadhead prince nymph'] },
  { name: 'Beadhead Copper John', category: 'fly', aliases: ['bh copper john'] },
  { name: 'Beadhead Hares Ear', category: 'fly', aliases: ['bh grhe', 'beadhead hares ear'] },
  { name: 'Beadhead Caddis Pupa', category: 'fly', aliases: ['bh caddis pupa'] },
  { name: 'Beadhead Stonefly', category: 'fly', aliases: ['bh stonefly'] },
  { name: 'Black Fly Nymph', category: 'fly', aliases: ['black fly nymph'] },
  { name: 'Black Zonker', category: 'fly', aliases: ['black zonker streamer'] },
  { name: 'BWO Nymph', category: 'fly', aliases: ['blue winged olive nymph'] },
  { name: 'Caddis Larva', category: 'fly', aliases: ['caddis larva nymph'] },
  { name: 'Caddis Pupa', category: 'fly', aliases: ['caddis pupa nymph'] },
  { name: 'Cased Caddis Gold', category: 'fly', aliases: ['cased caddis gold bead'] },
  { name: 'Copper John Red', category: 'fly', aliases: ['red copper john'] },
  { name: 'Copper John Green', category: 'fly', aliases: ['green copper john'] },
  { name: 'Crane Fly Larva', category: 'fly', aliases: ['crane fly larva nymph', 'leatherjacket'] },
  { name: 'Dancing Caddis', category: 'fly', aliases: ['dancing caddis nymph'] },
  { name: 'Euro Pheasant Tail', category: 'fly', aliases: ['euro ptn'] },
  { name: 'Euro Hares Ear', category: 'fly', aliases: ['euro grhe'] },
  { name: 'Extra Nymph', category: 'fly', aliases: ['extra nymph fly'] },
  { name: 'Flashback Copper John', category: 'fly', aliases: ['flashback copper john'] },
  { name: 'Flashback Prince', category: 'fly', aliases: ['flashback prince'] },
  { name: 'Free Living Caddis', category: 'fly', aliases: ['free living caddis nymph', 'rhyacophila dorsalis'] },
  { name: 'Gold Bead Buzzer', category: 'fly', aliases: ['gold bead buzzer', 'gb buzzer'] },
  { name: 'Gold Bead Damsel', category: 'fly', aliases: ['gb damsel', 'beadhead damsel'] },
  { name: 'Gold Bead Montana', category: 'fly', aliases: ['gb montana', 'beadhead montana'] },
  { name: 'Goldhead Bugger', category: 'fly', aliases: ['goldhead woolly bugger'] },
  { name: 'Green Stonefly', category: 'fly', aliases: ['green stonefly nymph'] },
  { name: 'Grey Scud', category: 'fly', aliases: ['grey scud nymph', 'freshwater shrimp'] },
  { name: 'Hares Ear Flashback Beadhead', category: 'fly', aliases: ['bh flashback grhe'] },
  { name: 'Hot Spot Hares Ear', category: 'fly', aliases: ['hot spot grhe'] },
  { name: 'Imitation Caddis', category: 'fly', aliases: ['imitation caddis nymph'] },
  { name: 'Jig Pheasant Tail', category: 'fly', aliases: ['jig pheasant tail nymph'] },
  { name: 'Jig Hares Ear', category: 'fly', aliases: ['jig hares ear nymph'] },
  { name: 'Jig Perdigon', category: 'fly', aliases: ['jig perdigon nymph'] },
  { name: 'Jig Frenchie', category: 'fly', aliases: ['jig frenchie nymph'] },
  { name: 'Large Olive Nymph', category: 'fly', aliases: ['large olive nymph'] },
  { name: 'Mayfly Nymph', category: 'fly', aliases: ['mayfly nymph', 'ephemera nymph'] },
  { name: 'Micro Caddis', category: 'fly', aliases: ['micro caddis nymph'] },
  { name: 'Olive Caddis Pupa', category: 'fly', aliases: ['olive caddis pupa'] },
  { name: 'Olive Caddis Larva', category: 'fly', aliases: ['olive caddis larva'] },
  { name: 'Peeping Caddis', category: 'fly', aliases: ['peeping caddis nymph'] },
  { name: 'Pheasant Tail Jig', category: 'fly', aliases: ['ptn jig'] },
  { name: 'Pheasant Tail Olive', category: 'fly', aliases: ['olive ptn'] },
  { name: 'Pheasant Tail Flashback', category: 'fly', aliases: ['ptn flashback'] },
  { name: 'Pupa Caddis', category: 'fly', aliases: ['pupa caddis nymph'] },
  { name: 'Red Tag Nymph', category: 'fly', aliases: ['red tag nymph'] },
  { name: 'Sedge Larva', category: 'fly', aliases: ['sedge larva nymph'] },
  { name: 'Sedge Pupa Nymph', category: 'fly', aliases: ['sedge pupa nymph'] },
  { name: 'Slotted Bead Pheasant Tail', category: 'fly', aliases: ['slotted bead ptn'] },
  { name: 'Small Olive Nymph', category: 'fly', aliases: ['small olive nymph'] },
  { name: 'Stonefly Nymph Gold', category: 'fly', aliases: ['gold bead stonefly'] },
  { name: 'Tungsten Bead Pheasant Tail', category: 'fly', aliases: ['tungsten ptn', 'tungsten bead ptn'] },
  { name: 'Tungsten Hares Ear', category: 'fly', aliases: ['tungsten grhe'] },
  { name: 'Tungsten Perdigon', category: 'fly', aliases: ['tungsten perdigon'] },
  { name: 'Tungsten Jig Nymph', category: 'fly', aliases: ['tungsten jig nymph'] },
  { name: 'UV Nymph', category: 'fly', aliases: ['uv nymph fly'] },
  { name: 'Water Boatman Nymph', category: 'fly', aliases: ['water boatman nymph', 'corixa nymph'] },
  { name: 'Yellow Nymph', category: 'fly', aliases: ['yellow nymph fly'] },
  { name: 'Zebra Midge Black', category: 'fly', aliases: ['black zebra midge'] },
  { name: 'Zebra Midge Red', category: 'fly', aliases: ['red zebra midge'] },
  { name: 'Zebra Midge Olive', category: 'fly', aliases: ['olive zebra midge'] },

  // === Additional North Country Spiders / soft hackles ===
  { name: 'Black & Peacock Spider', category: 'fly', aliases: ['black peacock soft hackle'] },
  { name: 'Black Spider', category: 'fly', aliases: ['black spider north country'] },
  { name: 'Blae & Black', category: 'fly', aliases: ['blae and black', 'blae black'] },
  { name: 'Blae & Blue', category: 'fly', aliases: ['blae and blue', 'blae blue'] },
  { name: 'Blue Dun Spider', category: 'fly', aliases: ['blue dun soft hackle'] },
  { name: 'Cinnamon Fly', category: 'fly', aliases: ['cinnamon fly spider'] },
  { name: 'Dark Watchet', category: 'fly', aliases: ['dark watchet spider'] },
  { name: 'Dor Beetle', category: 'fly', aliases: ['dor beetle fly'] },
  { name: 'Duns Spider', category: 'fly', aliases: ['duns soft hackle'] },
  { name: 'Grouse & Orange', category: 'fly', aliases: ['grouse orange', 'grouse and orange'] },
  { name: 'Grouse & Claret', category: 'fly', aliases: ['grouse claret spider'] },
  { name: 'Hares Lug', category: 'fly', aliases: ['hares lug spider', 'hares lug soft hackle'] },
  { name: 'Light Watchet', category: 'fly', aliases: ['light watchet spider'] },
  { name: 'Magpie Tail', category: 'fly', aliases: ['magpie tail spider'] },
  { name: 'Mole Fly', category: 'fly', aliases: ['mole fly spider', 'mole fur soft hackle'] },
  { name: 'Orange Partridge', category: 'fly', aliases: ['orange partridge spider'] },
  { name: 'Partridge & Hares Lug', category: 'fly', aliases: ['partridge hares lug'] },
  { name: 'Partridge & Orange Spider', category: 'fly', aliases: ['partridge orange spider'] },
  { name: 'Partridge & Yellow Spider', category: 'fly', aliases: ['partridge yellow spider'] },
  { name: 'Purple Partridge', category: 'fly', aliases: ['purple partridge spider'] },
  { name: 'Red & Black Spider', category: 'fly', aliases: ['red black spider'] },
  { name: 'Red Spinner Spider', category: 'fly', aliases: ['red spinner soft hackle'] },
  { name: 'Snipe & Purple Spider', category: 'fly', aliases: ['snipe purple spider'] },
  { name: 'Starling & Purple', category: 'fly', aliases: ['starling purple spider'] },
  { name: 'Stone Fly Spider', category: 'fly', aliases: ['stone fly soft hackle'] },
  { name: 'Swan & Blue', category: 'fly', aliases: ['swan blue spider'] },
  { name: 'Woodcock & Hares Lug', category: 'fly', aliases: ['woodcock hares lug'] },
  { name: 'Yellow Sally Spider', category: 'fly', aliases: ['yellow sally soft hackle'] },

  // === Additional loch / stillwater wet flies ===
  { name: 'Alexandra Wet', category: 'fly', aliases: ['alexandra wet fly'] },
  { name: 'Bibio Wet', category: 'fly', aliases: ['bibio wet fly'] },
  { name: 'Black & Peacock Wet', category: 'fly', aliases: ['black peacock wet'] },
  { name: 'Black Pennell Wet', category: 'fly', aliases: ['black pennell wet'] },
  { name: 'Black Zulu Dry', category: 'fly', aliases: ['black zulu dry fly'] },
  { name: 'Blae & Black Wet', category: 'fly', aliases: ['blae black wet'] },
  { name: 'Blue Zulu', category: 'fly', aliases: ['blue zulu wet'] },
  { name: 'Bumble Wet', category: 'fly', aliases: ['bumble wet fly'] },
  { name: 'Bush Bumble', category: 'fly', aliases: ['bush bumble fly'] },
  { name: 'Butcher Wet', category: 'fly', aliases: ['butcher wet fly'] },
  { name: 'Claret Bumble Loch', category: 'fly', aliases: ['claret bumble loch fly'] },
  { name: 'Coch-a-bonddhu Wet', category: 'fly', aliases: ['coch wet', 'bramble wet'] },
  { name: 'Culcron', category: 'fly', aliases: ['culcron fly'] },
  { name: 'Dabchick', category: 'fly', aliases: ['dabchick wet fly'] },
  { name: 'Fiery Brown Wet', category: 'fly', aliases: ['fiery brown wet fly'] },
  { name: 'Gosling Wet', category: 'fly', aliases: ['gosling wet fly'] },
  { name: 'Greenwells Glory Wet', category: 'fly', aliases: ['greenwells wet', 'greenwell wet'] },
  { name: 'Grouse & Claret Wet', category: 'fly', aliases: ['grouse claret wet'] },
  { name: 'Hares Ear Wet', category: 'fly', aliases: ['hares ear wet fly'] },
  { name: 'Heather Fly', category: 'fly', aliases: ['heather fly wet', 'heather fly bibio'] },
  { name: 'Hog Bumble', category: 'fly', aliases: ['hog bumble fly'] },
  { name: 'Jenny Spinner Wet', category: 'fly', aliases: ['jenny spinner wet'] },
  { name: 'Ke He', category: 'fly', aliases: ['ke he fly'] },
  { name: 'Kingfisher Butcher Wet', category: 'fly', aliases: ['kingfisher butcher wet'] },
  { name: 'Loch Ordie Wet', category: 'fly', aliases: ['loch ordie wet fly'] },
  { name: 'Mallard & Claret Loch', category: 'fly', aliases: ['mallard claret loch'] },
  { name: 'March Brown Wet Fly', category: 'fly', aliases: ['march brown wet fly pattern'] },
  { name: 'Olive Bumble', category: 'fly', aliases: ['olive bumble fly'] },
  { name: 'Olive Dabchick', category: 'fly', aliases: ['olive dabchick'] },
  { name: 'Olive Pennell', category: 'fly', aliases: ['olive pennell wet'] },
  { name: 'Peacock & Black', category: 'fly', aliases: ['peacock black wet'] },
  { name: 'Peacock & Red', category: 'fly', aliases: ['peacock red wet'] },
  { name: 'Peter Ross Wet', category: 'fly', aliases: ['peter ross wet fly'] },
  { name: 'Red Bumble', category: 'fly', aliases: ['red bumble fly'] },
  { name: 'Red Palmer', category: 'fly', aliases: ['red palmer wet'] },
  { name: 'Silver Invicta Wet', category: 'fly', aliases: ['silver invicta wet fly'] },
  { name: 'Soldier Palmer', category: 'fly', aliases: ['soldier palmer wet'] },
  { name: 'Stoats Tail', category: 'fly', aliases: ['stoats tail wet'] },
  { name: 'Teal & Green', category: 'fly', aliases: ['teal green wet'] },
  { name: 'Viva Wet', category: 'fly', aliases: ['viva wet fly'] },
  { name: 'Wickhams Fancy Wet', category: 'fly', aliases: ['wickhams wet', 'wickham fancy wet'] },
  { name: 'Zulu Wet', category: 'fly', aliases: ['zulu wet fly'] },

  // === Additional salmon & sea trout flies ===
  { name: 'Alistair', category: 'fly', aliases: ['alistair salmon'] },
  { name: 'Bann Special', category: 'fly', aliases: ['bann special salmon'] },
  { name: 'Black Doctor', category: 'fly', aliases: ['black doctor salmon'] },
  { name: 'Black Frances', category: 'fly', aliases: ['black frances salmon'] },
  { name: 'Blue Charm Double', category: 'fly', aliases: ['blue charm double'] },
  { name: 'Blue Doctor', category: 'fly', aliases: ['blue doctor salmon'] },
  { name: 'Butcher Salmon', category: 'fly', aliases: ['butcher salmon fly'] },
  { name: 'Cascade Double', category: 'fly', aliases: ['cascade double salmon'] },
  { name: 'Collie Dog', category: 'fly', aliases: ['collie dog salmon', 'collie dog tube'] },
  { name: 'Conon Mudler', category: 'fly', aliases: ['conon muddler salmon'] },
  { name: 'Cosby Gee', category: 'fly', aliases: ['cosby gee salmon'] },
  { name: 'Currys Red Shrimp', category: 'fly', aliases: ['currys red shrimp salmon'] },
  { name: 'Dunkeld Salmon', category: 'fly', aliases: ['dunkeld salmon fly'] },
  { name: 'Elisha', category: 'fly', aliases: ['elisha salmon'] },
  { name: 'Faery Queen', category: 'fly', aliases: ['faery queen salmon'] },
  { name: 'Garry Dog Salmon', category: 'fly', aliases: ['garry dog salmon fly'] },
  { name: 'Gold Body Willie Gunn', category: 'fly', aliases: ['gold body willie gunn'] },
  { name: 'Green Highlander', category: 'fly', aliases: ['green highlander salmon'] },
  { name: 'Green Machine', category: 'fly', aliases: ['green machine salmon'] },
  { name: 'Garry Dog Willie Gunn', category: 'fly', aliases: ['garry dog willie gunn'] },
  { name: 'Hairy Mary Double', category: 'fly', aliases: ['hairy mary double'] },
  { name: 'Harley Davidson', category: 'fly', aliases: ['harley davidson salmon'] },
  { name: 'Jock Scott', category: 'fly', aliases: ['jock scott salmon'] },
  { name: 'Jungle Cock', category: 'fly', aliases: ['jungle cock salmon'] },
  { name: 'Kinross Willie Gunn', category: 'fly', aliases: ['kinross willie gunn'] },
  { name: 'Logie', category: 'fly', aliases: ['logie salmon'] },
  { name: 'Munro Killer', category: 'fly', aliases: ['munro killer salmon'] },
  { name: 'Ness C', category: 'fly', aliases: ['ness c salmon'] },
  { name: 'Orange Garry', category: 'fly', aliases: ['orange garry salmon'] },
  { name: 'Park Fly', category: 'fly', aliases: ['park fly salmon'] },
  { name: 'Posh Tosh', category: 'fly', aliases: ['posh tosh salmon'] },
  { name: 'Red Frances', category: 'fly', aliases: ['red frances salmon'] },
  { name: 'Red Setter', category: 'fly', aliases: ['red setter salmon'] },
  { name: 'Silver Doctor', category: 'fly', aliases: ['silver doctor salmon'] },
  { name: 'Silver Stoat Double', category: 'fly', aliases: ['silver stoat double'] },
  { name: 'Silver Wilkinson', category: 'fly', aliases: ['silver wilkinson salmon'] },
  { name: 'Stoats Tail Double', category: 'fly', aliases: ['stoats tail double'] },
  { name: 'Suas Fork', category: 'fly', aliases: ['suas fork salmon'] },
  { name: 'Tayside Fly', category: 'fly', aliases: ['tayside salmon fly'] },
  { name: 'Teesfly', category: 'fly', aliases: ['teesfly salmon'] },
  { name: 'Thunder & Lightning', category: 'fly', aliases: ['thunder and lightning salmon'] },
  { name: 'Tosh', category: 'fly', aliases: ['tosh salmon'] },
  { name: 'Turret Fly', category: 'fly', aliases: ['turret fly salmon'] },
  { name: 'Waddington', category: 'fly', aliases: ['waddington salmon', 'waddington tube'] },
  { name: 'Willie Gunn Tube', category: 'fly', aliases: ['willie gunn tube'] },
  { name: 'Yellow Ally', category: 'fly', aliases: ['yellow allys shrimp'] },
  { name: 'Yellow Torrish', category: 'fly', aliases: ['yellow torrish salmon'] },
  { name: 'Yogi Bear', category: 'fly', aliases: ['yogi bear salmon'] },
  { name: 'Zebra Salmon', category: 'fly', aliases: ['zebra salmon fly'] },

  // === Grayling specific patterns ===
  { name: 'Grayling Bug', category: 'fly', aliases: ['grayling bug nymph'] },
  { name: 'Pink Shrimp', category: 'fly', aliases: ['pink shrimp grayling', 'grayling pink shrimp'] },
  { name: 'Klinkhammer Gray', category: 'fly', aliases: ['gray klinkhammer'] },
  { name: 'Tungsten Pink Bug', category: 'fly', aliases: ['tungsten pink bug grayling'] },
  { name: 'Czech Nymph', category: 'fly', aliases: ['czech nymph fly', 'euro czech nymph'] },
  { name: 'Rolled Muddler', category: 'fly', aliases: ['rolled muddler minnow'] },
  { name: 'Beadhead Gray Bug', category: 'fly', aliases: ['gray bug grayling'] },
  { name: 'Hot Bead Pheasant Tail', category: 'fly', aliases: ['hot bead ptn'] },
  { name: 'Hot Bead Hares Ear', category: 'fly', aliases: ['hot bead grhe'] },
  { name: 'Olive Bug', category: 'fly', aliases: ['olive bug nymph'] },
  { name: 'Pink Squirm', category: 'fly', aliases: ['pink squirmy grayling'] },
  { name: 'Red Tag Grayling', category: 'fly', aliases: ['red tag grayling fly'] },
  { name: 'Slotted Tungsten Bug', category: 'fly', aliases: ['slotted tungsten bug'] },
  { name: 'Tungsten Gray Bug', category: 'fly', aliases: ['tungsten gray bug'] },
  { name: 'UV Pink Bug', category: 'fly', aliases: ['uv pink bug grayling'] },
  { name: 'Yellow Bug', category: 'fly', aliases: ['yellow bug grayling'] },

  // === Additional sea trout / night flies ===
  { name: 'Alexander Sea Trout', category: 'fly', aliases: ['alexandra sea trout'] },
  { name: 'Black Pennell Sea Trout', category: 'fly', aliases: ['black pennell sea trout'] },
  { name: 'Bodkin', category: 'fly', aliases: ['bodkin sea trout'] },
  { name: 'Coch-y-Bonddhu Sea Trout', category: 'fly', aliases: ['coch sea trout'] },
  { name: 'Dark Mackerel', category: 'fly', aliases: ['dark mackerel sea trout'] },
  { name: 'Dunkeld Sea Trout', category: 'fly', aliases: ['dunkeld sea trout'] },
  { name: 'Fiery Brown Sea Trout', category: 'fly', aliases: ['fiery brown sea trout'] },
  { name: 'Gosling Sea Trout', category: 'fly', aliases: ['gosling sea trout'] },
  { name: 'Greenwells Sea Trout', category: 'fly', aliases: ['greenwells sea trout'] },
  { name: 'Hares Ear Sea Trout', category: 'fly', aliases: ['hares ear sea trout'] },
  { name: 'Jenny Morgan', category: 'fly', aliases: ['jenny morgan sea trout'] },
  { name: 'Kingfisher Sea Trout', category: 'fly', aliases: ['kingfisher sea trout'] },
  { name: 'Mallard & Claret Sea Trout', category: 'fly', aliases: ['mallard claret sea trout'] },
  { name: 'Medicine Fly', category: 'fly', aliases: ['medicine sea trout'] },
  { name: 'Muddler Minnow Sea Trout', category: 'fly', aliases: ['muddler sea trout night'] },
  { name: 'Peter Ross Sea Trout', category: 'fly', aliases: ['peter ross sea trout'] },
  { name: 'Red Palmer Sea Trout', category: 'fly', aliases: ['red palmer sea trout'] },
  { name: 'Silver Doctor Sea Trout', category: 'fly', aliases: ['silver doctor sea trout'] },
  { name: 'Slob Mackerel', category: 'fly', aliases: ['slob mackerel sea trout'] },
  { name: 'Soldier Palmer Sea Trout', category: 'fly', aliases: ['soldier palmer sea trout'] },
  { name: 'Stoats Tail Sea Trout', category: 'fly', aliases: ['stoats tail sea trout'] },
  { name: 'Teal Blue & Silver Sea Trout', category: 'fly', aliases: ['teal blue silver sea trout'] },
  { name: 'Teal & Green Sea Trout', category: 'fly', aliases: ['teal green sea trout'] },
  { name: 'Zulu Sea Trout', category: 'fly', aliases: ['zulu sea trout'] },

  // === Pike fly patterns ===
  { name: 'Pike Fly', category: 'fly', aliases: ['pike fly pattern'] },
  { name: 'Baitfish Fly', category: 'fly', aliases: ['baitfish fly pattern', 'baitfish imitation'] },
  { name: 'Deceiver Pike', category: 'fly', aliases: ['deceiver pike fly'] },
  { name: 'Clouser Pike', category: 'fly', aliases: ['clouser pike fly'] },
  { name: 'Whistler', category: 'fly', aliases: ['whistler fly', 'whistler pike'] },
  { name: 'Bunny Fly', category: 'fly', aliases: ['bunny fly pike', 'rabbit strip fly'] },
  { name: 'Squimp', category: 'fly', aliases: ['squimp fly'] },
  { name: 'Barred Flash', category: 'fly', aliases: ['barred flash fly'] },
  { name: 'Hollow Fleye', category: 'fly', aliases: ['hollow fleye fly', 'hollow fly'] },
  { name: 'Surf Candy', category: 'fly', aliases: ['surf candy fly'] },
  { name: 'Spearhead Fly', category: 'fly', aliases: ['spearhead pike fly'] },
  { name: 'Pike Popper Fly', category: 'fly', aliases: ['pike popper', 'popper pike fly'] },
  { name: 'Pike Tube Fly', category: 'fly', aliases: ['pike tube fly'] },
  { name: 'Flashabou Fly', category: 'fly', aliases: ['flashabou pike fly'] },
  { name: 'Articulated Fly', category: 'fly', aliases: ['articulated pike fly', 'articulated streamer'] },

  // === Saltwater fly patterns ===
  { name: 'Saltwater Fly', category: 'fly', aliases: ['saltwater fly pattern'] },
  { name: 'Clouser Minnow Salt', category: 'fly', aliases: ['clouser saltwater'] },
  { name: 'Deceiver Salt', category: 'fly', aliases: ['deceiver saltwater'] },
  { name: 'Surf Candy Sand Eel', category: 'fly', aliases: ['surf candy sand eel'] },
  { name: 'Sand Eel Fly', category: 'fly', aliases: ['sandeel fly', 'sand eel imitation'] },
  { name: 'Bass Fly', category: 'fly', aliases: ['bass fly pattern', 'sea bass fly'] },
  { name: 'Crab Fly', category: 'fly', aliases: ['crab fly pattern', 'merkin crab'] },
  { name: 'Shrimp Fly Salt', category: 'fly', aliases: ['shrimp fly saltwater'] },
  { name: 'Squid Fly', category: 'fly', aliases: ['squid fly pattern'] },
  { name: 'Mackerel Fly', category: 'fly', aliases: ['mackerel fly pattern'] },
  { name: 'Pollock Fly', category: 'fly', aliases: ['pollock fly pattern'] },
  { name: 'Bucktail Deceiver', category: 'fly', aliases: ['bucktail deceiver saltwater'] },
  { name: 'Flatwing', category: 'fly', aliases: ['flatwing fly', 'flatwing streamer'] },
  { name: 'Gurgler Salt', category: 'fly', aliases: ['gurgler saltwater'] },
  { name: 'Popper Fly Salt', category: 'fly', aliases: ['popper fly saltwater'] },
  { name: 'Slammer Fly', category: 'fly', aliases: ['slammer fly saltwater'] },
  { name: 'Gotcha', category: 'fly', aliases: ['gotcha fly', 'gotcha bonefish'] },
  { name: 'Crazy Charlie', category: 'fly', aliases: ['crazy charlie fly'] },
  { name: 'Del Brown Permit', category: 'fly', aliases: ['del brown permit fly'] },
];

// ============================================================
// LURES — comprehensive UK popular lures
// ============================================================
export const LURES: BaitEntry[] = [
  { name: 'Mepps Aglia', category: 'lure', aliases: ['mepps', 'aglia', 'mepps aglia spinner'] },
  { name: 'Mepps Comet', category: 'lure', aliases: ['mepps comet spinner'] },
  { name: 'Mepps Longcast', category: 'lure', aliases: ['mepps longcast spinner'] },
  { name: 'Mepps Black Fury', category: 'lure', aliases: ['black fury', 'mepps black fury'] },
  { name: 'Abu Toby', category: 'lure', aliases: ['toby', 'abu toby spoon'] },
  { name: 'Abu Droppen', category: 'lure', aliases: ['droppen', 'abu droppen spoon'] },
  { name: 'Abu Hi-Lo', category: 'lure', aliases: ['hi-lo', 'hi lo'] },
  { name: 'Abu Toro', category: 'lure', aliases: ['toro', 'abu toro spoon'] },
  { name: 'Blue Fox Super Vibrax', category: 'lure', aliases: ['blue fox', 'vibrax', 'super vibrax'] },
  { name: 'Rooster Tail', category: 'lure', aliases: ['rooster tail spinner'] },
  { name: 'Panther Martin', category: 'lure', aliases: ['panther martin spinner'] },
  { name: 'Dexter Wedge', category: 'lure', aliases: ['dexter', 'wedge'] },
  { name: 'Sprat Spoon', category: 'lure', aliases: ['sprat', 'sprat spoon lure'] },
  { name: 'Salmo Spoon', category: 'lure', aliases: ['salmo', 'salmo spoon lure'] },
  { name: 'Trolling Spoon', category: 'lure', aliases: ['trolling spoon lure'] },
  { name: 'Rapala Original Floater', category: 'lure', aliases: ['rapala', 'original floater', 'rapala floater'] },
  { name: 'Rapala Jointed', category: 'lure', aliases: ['rapala jointed', 'jointed rapala'] },
  { name: 'Rapala X-Rap', category: 'lure', aliases: ['x-rap', 'xrap', 'rapala xrap'] },
  { name: 'Rapala Count Down', category: 'lure', aliases: ['countdown', 'rapala countdown', 'rapala cd'] },
  { name: 'Rapala Husky Jerk', category: 'lure', aliases: ['husky jerk', 'husky'] },
  { name: 'Rapala Shadow Rap', category: 'lure', aliases: ['shadow rap', 'shadow'] },
  { name: 'Rapala Scatter Rap', category: 'lure', aliases: ['scatter rap', 'scatter'] },
  { name: 'Heddon Super Spook', category: 'lure', aliases: ['super spook', 'heddon spook', 'spook'] },
  { name: 'Lucky Craft Pointer', category: 'lure', aliases: ['lucky craft', 'pointer', 'lucky pointer'] },
  { name: 'Yo-Zuri Crystal Minnow', category: 'lure', aliases: ['yo-zuri', 'crystal minnow', 'yo zuri'] },
  { name: 'Yo-Zuri Mag Minnow', category: 'lure', aliases: ['mag minnow'] },
  { name: 'Deep Diving Crank', category: 'lure', aliases: ['deep crank', 'deep diver', 'deep diving crankbait'] },
  { name: 'Shallow Crank', category: 'lure', aliases: ['shallow crankbait', 'shallow diver'] },
  { name: 'Lipless Crank', category: 'lure', aliases: ['lipless crankbait', 'rattle trap'] },
  { name: 'Square Bill', category: 'lure', aliases: ['square bill crankbait'] },
  { name: 'Rat-L-Trap', category: 'lure', aliases: ['rat l trap', 'rattle trap'] },
  { name: 'Bandit', category: 'lure', aliases: ['bandit crankbait'] },
  { name: 'Hard Jerkbait', category: 'lure', aliases: ['jerkbait', 'hard jerk'] },
  { name: 'Soft Jerkbait', category: 'lure', aliases: ['soft jerk', 'soft jerkbait'] },
  { name: 'Glide Bait', category: 'lure', aliases: ['glide', 'glider'] },
  { name: 'Berkley PowerBait Jerk Shad', category: 'lure', aliases: ['powerbait jerk shad', 'jerk shad'] },
  { name: 'Curly Tail Grub', category: 'lure', aliases: ['grub', 'curly tail', 'twintail grub'] },
  { name: 'Twintail', category: 'lure', aliases: ['twin tail', 'double tail grub'] },
  { name: 'Senko', category: 'lure', aliases: ['senko worm', 'gary yamamoto senko'] },
  { name: 'Ned Rig', category: 'lure', aliases: ['ned', 'ned rig jig'] },
  { name: 'Creature Bait', category: 'lure', aliases: ['creature', 'creature bait soft plastic'] },
  { name: 'Tube Bait', category: 'lure', aliases: ['tube', 'tube jig'] },
  { name: 'Swimbait Soft', category: 'lure', aliases: ['soft swimbait'] },
  { name: 'Bucktail Jig', category: 'lure', aliases: ['bucktail', 'bucktail jig lure'] },
  { name: 'Round Jighead', category: 'lure', aliases: ['jighead', 'round jig head'] },
  { name: 'Football Jig', category: 'lure', aliases: ['football jig head'] },
  { name: 'Swim Jig', category: 'lure', aliases: ['swim jig head'] },
  { name: 'Finesse Jig', category: 'lure', aliases: ['finesse jig head'] },
  { name: 'Ned Jig', category: 'lure', aliases: ['ned jig head'] },
  { name: 'Hard Swimbait', category: 'lure', aliases: ['hard swimbait'] },
  { name: 'Paddletail', category: 'lure', aliases: ['paddle tail', 'paddletail soft plastic'] },
  { name: 'Hollow Body Swimbait', category: 'lure', aliases: ['hollow body', 'hollow swimbait'] },
  { name: 'Multi-Joint Swimbait', category: 'lure', aliases: ['multi joint', 'jointed swimbait'] },
  { name: 'Popper', category: 'lure', aliases: ['popper lure', 'topwater popper'] },
  { name: 'Walker', category: 'lure', aliases: ['walking bait', 'walker lure'] },
  { name: 'Prop Bait', category: 'lure', aliases: ['prop', 'propeller bait'] },
  { name: 'Buzzbait', category: 'lure', aliases: ['buzz bait', 'buzzbait lure'] },
  { name: 'Frog Lure', category: 'lure', aliases: ['frog', 'hollow frog', 'topwater frog'] },
  { name: 'Stickbait', category: 'lure', aliases: ['stick bait', 'walk the dog'] },
  { name: 'Vibration Bait', category: 'lure', aliases: ['vib', 'vibration lure', 'rattling vib'] },
  { name: 'Rattling Vib', category: 'lure', aliases: ['rattle vib', 'rattling lure'] },
  { name: 'Spinnerbait', category: 'lure', aliases: ['spinner bait', 'safety pin spinner'] },
  { name: 'Chatterbait', category: 'lure', aliases: ['chatter bait', 'bladed jig'] },
  { name: 'Bladed Jig', category: 'lure', aliases: ['bladed swim jig'] },
  { name: 'Soft Plastic Shad', category: 'lure', aliases: ['shad soft plastic', 'shad imitation'] },
  { name: 'Soft Plastic Minnow', category: 'lure', aliases: ['minnow soft plastic'] },
  { name: 'Soft Plastic Lizard', category: 'lure', aliases: ['lizard soft plastic'] },
  { name: 'Soft Plastic Worm', category: 'lure', aliases: ['worm soft plastic', 'ribbon tail worm'] },
  { name: 'Drop Shot Worm', category: 'lure', aliases: ['drop shot', 'dropshot worm'] },
  { name: 'Ned Bait', category: 'lure', aliases: ['ned bait soft plastic'] },
  { name: 'Jigging Rap', category: 'lure', aliases: ['jigging rapala', 'jig rap'] },
  { name: 'Vertical Jig', category: 'lure', aliases: ['vertical jigging lure'] },
  { name: 'Slab Spoon', category: 'lure', aliases: ['slab', 'slab spoon lure'] },
  { name: 'Casting Spoon', category: 'lure', aliases: ['casting spoon lure'] },
  { name: 'Weedless Spoon', category: 'lure', aliases: ['weedless spoon lure'] },
  { name: 'Savage Gear Sandeel', category: 'lure', aliases: ['savage gear', 'sandeel lure', 'savage gear sandeel'] },
  { name: 'Savage Gear Rotex', category: 'lure', aliases: ['rotex', 'savage gear rotex'] },
  { name: 'Fiiish Black Minnow', category: 'lure', aliases: ['black minnow', 'fiiish', 'fiiish black minnow'] },
  { name: 'Duo Tide Minnow', category: 'lure', aliases: ['duo', 'tide minnow', 'duo tide minnow'] },
  { name: 'IMA Sasuke', category: 'lure', aliases: ['ima', 'sasuke', 'ima sasuke'] },
  { name: 'Megabass Vision 110', category: 'lure', aliases: ['megabass', 'vision 110', 'megabass vision'] },
  { name: 'Jackall Squad Minnow', category: 'lure', aliases: ['jackall', 'squad minnow'] },
  { name: 'Westin Swim', category: 'lure', aliases: ['westin', 'westin swim lure'] },
  { name: 'Daiwa Salt Pro Minnow', category: 'lure', aliases: ['daiwa', 'salt pro minnow', 'daiwa spm'] },
  { name: 'Tsunami Talkin Popper', category: 'lure', aliases: ['tsunami', 'talkin popper'] },
  { name: 'Gulp Sandworm', category: 'lure', aliases: ['gulp', 'gulp sandworm lure'] },
  { name: 'Berkley Gulp Minnow', category: 'lure', aliases: ['gulp minnow', 'berkley gulp'] },
  { name: 'Z-Man Finesse TRD', category: 'lure', aliases: ['z-man', 'finesse trd', 'zman trd'] },
  { name: 'Keitech Fat Swing Impact', category: 'lure', aliases: ['keitech', 'fat swing impact', 'keitech swing impact'] },
  { name: 'Keitech Easy Shiner', category: 'lure', aliases: ['easy shiner', 'keitech easy shiner'] },
  { name: 'Manns Jelly Worm', category: 'lure', aliases: ['manns', 'jelly worm', 'manns jelly worm'] },
  { name: 'Gummi Minnow', category: 'lure', aliases: ['gummi', 'gummi minnow soft plastic'] },
];

// ============================================================
// BAITS — standard coarse and sea baits
// ============================================================
export const BAITS: BaitEntry[] = [
  { name: 'Maggot', category: 'bait', aliases: ['maggots', 'squatt', 'pinkie', 'gentles'] },
  { name: 'Worm', category: 'bait', aliases: ['lobworm', 'dendrobaena', 'redworm', 'brandling'] },
  { name: 'Boilie', category: 'bait', aliases: ['boilies', 'bottom bait', 'pop-up boilie'] },
  { name: 'Pellet', category: 'bait', aliases: ['halibut pellet', 'expander pellet', 'micro pellet'] },
  { name: 'Sweetcorn', category: 'bait', aliases: ['corn', 'maize'] },
  { name: 'Bread', category: 'bait', aliases: ['bread flake', 'bread punch', 'crust', 'bread crust'] },
  { name: 'Luncheon Meat', category: 'bait', aliases: ['spam', 'meat', 'tinned meat'] },
  { name: 'Casters', category: 'bait', aliases: ['caster', 'maggot caster'] },
  { name: 'Hemp', category: 'bait', aliases: ['hempseed', 'hemp seed'] },
  { name: 'Tares', category: 'bait', aliases: ['tare'] },
  { name: 'Deadbait', category: 'bait', aliases: ['dead bait', 'dead fish bait', 'deadbait roach'] },
  { name: 'Livebait', category: 'bait', aliases: ['live bait', 'live fish', 'livebait roach'] },
  { name: 'Prawn', category: 'bait', aliases: ['shrimp bait', 'prawn bait'] },
  { name: 'Squid Bait', category: 'bait', aliases: ['squid strip', 'squid', 'squid tentacle'] },
  { name: 'Ragworm', category: 'bait', aliases: ['rag worm', 'king rag', 'ragworm bait'] },
  { name: 'Lugworm', category: 'bait', aliases: ['lug worm', 'black lug', 'blow lug'] },
  { name: 'Crab Bait', category: 'bait', aliases: ['peeler crab', 'soft crab', 'crab', 'hermit crab'] },
  { name: 'Mussel', category: 'bait', aliases: ['mussels', 'mussel bait'] },
  { name: 'Sand Eel Bait', category: 'bait', aliases: ['sand eel', 'sandeel bait'] },
  { name: 'Mackerel Strip', category: 'bait', aliases: ['mackerel bait', 'fish strip', 'mackerel fillet'] },
  { name: 'Paste', category: 'bait', aliases: ['trout paste', 'cheese paste', 'paste bait'] },
  { name: 'Cheese', category: 'bait', aliases: ['cheese bait'] },
  { name: 'Particles', category: 'bait', aliases: ['maize', 'chickpeas', 'tiger nuts', 'hempseed mix'] },
  { name: 'Fake Bait', category: 'bait', aliases: ['plastic corn', 'fake corn', 'artificial bait'] },
  { name: 'Hemp & Tares', category: 'bait', aliases: ['hemp and tares'] },
  { name: 'Worm & Caster', category: 'bait', aliases: ['worm and caster', 'worm caster'] },
  { name: 'Maggot & Caster', category: 'bait', aliases: ['maggot and caster'] },
  { name: 'Peanuts', category: 'bait', aliases: ['peanut', 'monkey nut'] },
  { name: 'Tigernuts', category: 'bait', aliases: ['tiger nut', 'tigernut'] },
  { name: 'Maple Peas', category: 'bait', aliases: ['maple pea'] },
  { name: 'Wheat', category: 'bait', aliases: ['wheat bait'] },
  { name: 'Perlon', category: 'bait', aliases: ['perlon bait'] },
  { name: 'Squid & Octopus', category: 'bait', aliases: ['squid octopus cocktail'] },
  { name: 'Black Lug Cocktail', category: 'bait', aliases: ['lug and squid', 'lug squid'] },
  { name: 'Mussel & Lug', category: 'bait', aliases: ['mussel lug cocktail'] },
  { name: 'Fish Gut', category: 'bait', aliases: ['fish guts', 'gut bait'] },
  { name: 'Clam', category: 'bait', aliases: ['clam bait', 'razor clam'] },
  { name: 'Razor Clam', category: 'bait', aliases: ['razorfish', 'razor clam bait'] },
  { name: 'Cockle', category: 'bait', aliases: ['cockle bait'] },
  { name: 'Limpet', category: 'bait', aliases: ['limpet bait'] },
  { name: 'Winkles', category: 'bait', aliases: ['winkle', 'periwinkle'] },
  { name: 'Sprat', category: 'bait', aliases: ['sprat bait', 'sprat deadbait'] },
  { name: 'Herring', category: 'bait', aliases: ['herring bait', 'herring deadbait'] },
  { name: 'Smelt Bait', category: 'bait', aliases: ['smelt deadbait'] },
  { name: 'Roach Deadbait', category: 'bait', aliases: ['roach deadbait'] },
  { name: 'Bleak Deadbait', category: 'bait', aliases: ['bleak deadbait'] },
  { name: 'Dace Deadbait', category: 'bait', aliases: ['dace deadbait'] },
];

// ============================================================
// ALL BAITS combined
// ============================================================
export const ALL_BAITS: BaitEntry[] = [...FLIES, ...LURES, ...BAITS];

// Search function for autocomplete
export function searchBaits(query: string, category?: BaitEntry['category'], limit = 50): BaitEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) {
    const pool = category ? ALL_BAITS.filter((b) => b.category === category) : ALL_BAITS;
    return pool.slice(0, limit);
  }
  const pool = category ? ALL_BAITS.filter((b) => b.category === category) : ALL_BAITS;
  return pool
    .filter((b) => {
      if (b.name.toLowerCase().includes(q)) return true;
      if (b.aliases?.some((a) => a.toLowerCase().includes(q))) return true;
      return false;
    })
    .slice(0, limit);
}

// Get category for a given bait name
export function getBaitCategory(name: string): BaitEntry['category'] | null {
  if (!name) return null;
  const lower = name.toLowerCase();
  const entry = ALL_BAITS.find(
    (b) => b.name.toLowerCase() === lower ||
    b.aliases?.some((a) => a.toLowerCase() === lower)
  );
  return entry?.category ?? null;
}
