// Comprehensive bait, lure, and fly database for UK fishing
// Each entry is a single item that can be searched by name or alias

export interface BaitEntry {
  name: string;
  category: 'lure' | 'fly' | 'float' | 'ledger' | 'bait' | 'other';
  aliases?: string[];
}

// ============================================================
// FLIES — comprehensive UK patterns
// ============================================================
export const FLIES: BaitEntry[] = [
  // Dry flies
  { name: 'Olive Klinkhammer', category: 'fly', aliases: ['klinkhammer', 'klink', 'olive klink'] },
  { name: 'Elk Hair Caddis', category: 'fly', aliases: ['elk hair', 'caddis dry', 'sedge dry'] },
  { name: 'Adams', category: 'fly', aliases: ['adams dry'] },
  { name: 'Mayfly Dun', category: 'fly', aliases: ['mayfly', 'green drake', 'ephemera'] },
  { name: 'Mayfly Spinner', category: 'fly', aliases: ['spent mayfly', 'spent gnat'] },
  { name: 'Green Drake', category: 'fly', aliases: ['green drake mayfly'] },
  { name: 'Spent Gnat', category: 'fly', aliases: ['spent spinner'] },
  { name: 'Greenwells Glory', category: 'fly', aliases: ['greenwell', 'greenwells'] },
  { name: 'Sherry Spinner', category: 'fly', aliases: ['sherry'] },
  { name: 'Blue Winged Olive', category: 'fly', aliases: ['bwo', 'blue wing olive'] },
  { name: 'Large Olive', category: 'fly', aliases: ['large olive dun'] },
  { name: 'Hopper', category: 'fly', aliases: ['grasshopper', 'hopper fly'] },
  { name: 'Beetle', category: 'fly', aliases: ['cockchafer', 'beetle fly'] },
  { name: 'Ant', category: 'fly', aliases: ['flying ant', 'ant fly'] },
  { name: 'Crane Fly', category: 'fly', aliases: ['daddy long legs', 'crane'] },
  { name: 'Hawthorn', category: 'fly', aliases: ['hawthorn fly'] },
  { name: 'Tups Indispensable', category: 'fly', aliases: ['tups', 'tups indisp'] },
  { name: 'Black Gnat', category: 'fly', aliases: ['gnat'] },
  { name: 'Griffiths Gnat', category: 'fly', aliases: ['griffith gnat'] },
  { name: 'Ginger Quill', category: 'fly', aliases: ['ginger'] },
  { name: 'Red Quill', category: 'fly', aliases: ['red quill'] },
  { name: 'Iron Blue Dun', category: 'fly', aliases: ['iron blue'] },
  { name: 'Pale Watery', category: 'fly', aliases: ['pale watery dun'] },
  { name: 'Medium Olive', category: 'fly', aliases: ['medium olive dun'] },
  { name: 'False March Brown', category: 'fly', aliases: ['march brown'] },
  { name: 'March Brown', category: 'fly', aliases: ['march brown dun'] },
  { name: 'Turkey Brown', category: 'fly', aliases: ['turkey brown nymph'] },
  { name: 'Welmans Fancy', category: 'fly', aliases: ['welmans'] },
  { name: 'Bumble', category: 'fly', aliases: ['heather fly', 'bumble fly'] },
  { name: 'Bibio', category: 'fly', aliases: ['heather fly bibio'] },
  { name: 'Claret Bumble', category: 'fly', aliases: ['claret'] },
  { name: 'Stout Hackle', category: 'fly', aliases: ['stout'] },
  { name: 'Loch Ordie', category: 'fly', aliases: ['ordie'] },
  { name: 'Zulu', category: 'fly', aliases: ['black zulu'] },
  { name: 'Black Pennell', category: 'fly', aliases: ['pennell'] },
  { name: 'Red Tag', category: 'fly', aliases: ['red tag dry'] },
  { name: 'Coch-a-bonddhu', category: 'fly', aliases: ['coch', 'bramble fly'] },
  { name: 'Gosling', category: 'fly', aliases: ['gosling dry'] },
  { name: 'Sedge', category: 'fly', aliases: ['caddis dry', 'sedge dry'] },
  { name: 'God Sedge', category: 'fly', aliases: ['god sedge caddis'] },
  { name: 'Cinnamon Sedge', category: 'fly', aliases: ['cinnamon caddis'] },
  { name: 'Grouse Wing', category: 'fly', aliases: ['grouse and claret'] },
  { name: 'Silver Sedge', category: 'fly', aliases: ['silver sedge caddis'] },
  { name: 'Pheasant Tail Dry', category: 'fly', aliases: ['pt dry'] },

  // Nymphs
  { name: 'Pheasant Tail Nymph', category: 'fly', aliases: ['ptn', 'pheasant tail', 'pt nymph'] },
  { name: 'Gold Ribbed Hares Ear', category: 'fly', aliases: ['grhe', 'hares ear', 'gold ribbed'] },
  { name: 'Hares Ear', category: 'fly', aliases: ['hares ear nymph'] },
  { name: 'Prince Nymph', category: 'fly', aliases: ['prince'] },
  { name: 'Copper John', category: 'fly', aliases: ['copper john nymph'] },
  { name: 'Zebra Midge', category: 'fly', aliases: ['zebra midge nymph'] },
  { name: 'Olive Nymph', category: 'fly', aliases: ['olive nymph'] },
  { name: 'Stonefly Nymph', category: 'fly', aliases: ['stonefly'] },
  { name: 'Cased Caddis', category: 'fly', aliases: ['cased caddis nymph'] },
  { name: 'Rhyacophila', category: 'fly', aliases: ['rhyacophila nymph', 'free living caddis'] },
  { name: 'Buzzer', category: 'fly', aliases: ['chironomid', 'midge pupa', 'buzzer nymph'] },
  { name: 'Bloodworm', category: 'fly', aliases: ['bloodworm nymph', 'red midge larva'] },
  { name: 'Jig Nymph', category: 'fly', aliases: ['jig', 'euro nymph'] },
  { name: 'Perdigon', category: 'fly', aliases: ['perdigon nymph', 'spanish nymph'] },
  { name: 'Frenchie', category: 'fly', aliases: ['french nymph'] },
  { name: 'Squirmy Wormy', category: 'fly', aliases: ['squirmie', 'squirmy'] },
  { name: 'San Juan Worm', category: 'fly', aliases: ['san juan', 'worm fly'] },
  { name: 'Epoxy Buzzer', category: 'fly', aliases: ['epoxy midge'] },
  { name: 'Cormorant Nymph', category: 'fly', aliases: ['cormorant'] },
  { name: 'Diawl Bach', category: 'fly', aliases: ['diawl', 'peeping diawl bach', 'diawl bach flashback'] },
  { name: 'Cats Whisker', category: 'fly', aliases: ['cat whisker', 'cats whiskers', 'mini cat', 'flash cat'] },
  { name: 'Blob', category: 'fly', aliases: ['blob fly', 'orange blob', 'tequila blob'] },
  { name: 'Damsel Nymph', category: 'fly', aliases: ['damsel', 'damselfly'] },
  { name: 'Montana Nymph', category: 'fly', aliases: ['montana'] },
  { name: 'Cress Bug', category: 'fly', aliases: ['cress beetle'] },
  { name: 'Corixa', category: 'fly', aliases: ['water boatman'] },
  { name: 'Shrimp Fly', category: 'fly', aliases: ['freshwater shrimp fly'] },
  { name: 'Olive Buzzer', category: 'fly', aliases: ['olive midge'] },
  { name: 'Black Buzzer', category: 'fly', aliases: ['black midge pupa'] },
  { name: 'Red Buzzer', category: 'fly', aliases: ['red midge pupa'] },
  { name: 'Ally Buzzer', category: 'fly', aliases: ['allys buzzer'] },
  { name: 'Sparkler Buzzer', category: 'fly', aliases: ['sparkler'] },
  { name: 'Squirmy Bug', category: 'fly', aliases: ['squirmy bug nymph'] },

  // Wet flies
  { name: 'Partridge & Orange', category: 'fly', aliases: ['partridge orange', 'partridge and orange'] },
  { name: 'Partridge & Yellow', category: 'fly', aliases: ['partridge yellow'] },
  { name: 'Snipe & Purple', category: 'fly', aliases: ['snipe purple', 'snipe and purple'] },
  { name: 'Waterhen Bloa', category: 'fly', aliases: ['waterhen', 'bloa'] },
  { name: 'Kingfisher Butcher', category: 'fly', aliases: ['butcher', 'kingfisher'] },
  { name: 'Dunkeld', category: 'fly', aliases: ['dunkeld wet'] },
  { name: 'Peter Ross', category: 'fly', aliases: ['peter ross wet'] },
  { name: 'Teal Blue & Silver', category: 'fly', aliases: ['teal blue silver'] },
  { name: 'Black Zulu Wet', category: 'fly', aliases: ['zulu wet'] },
  { name: 'Connemara Black', category: 'fly', aliases: ['connemara'] },
  { name: 'Claret Bumble Wet', category: 'fly', aliases: ['claret bumble wet'] },
  { name: 'Invicta', category: 'fly', aliases: ['invicta wet'] },
  { name: 'Mallard & Claret', category: 'fly', aliases: ['mallard claret'] },
  { name: 'March Brown Wet', category: 'fly', aliases: ['march brown wet fly'] },
  { name: 'Soft Hackle', category: 'fly', aliases: ['spider', 'north country spider', 'soft hackle fly'] },
  { name: 'Pheasant Tail Spider', category: 'fly', aliases: ['pt spider'] },
  { name: 'Snipe Bloa', category: 'fly', aliases: ['snipe bloa spider'] },
  { name: 'Partridge Spider', category: 'fly', aliases: ['partridge soft hackle'] },
  { name: 'Starling & Herl', category: 'fly', aliases: ['starling herl'] },
  { name: 'Grouse & Clove', category: 'fly', aliases: ['grouse clove'] },
  { name: 'Dotterel & Yellow', category: 'fly', aliases: ['dotterel'] },
  { name: 'Woodcock & Yellow', category: 'fly', aliases: ['woodcock'] },

  // Streamers & lures (fly)
  { name: 'Woolly Bugger', category: 'fly', aliases: ['woolly', 'bugger'] },
  { name: 'Muddler Minnow', category: 'fly', aliases: ['muddler'] },
  { name: 'Clouser Minnow', category: 'fly', aliases: ['clouser'] },
  { name: 'Deceiver', category: 'fly', aliases: ['lefty deceiver', 'deceiver fly'] },
  { name: 'Sculpin', category: 'fly', aliases: ['sculpin fly'] },
  { name: 'Zonker', category: 'fly', aliases: ['rabbit zonker', 'zonker fly'] },
  { name: 'Mickey Finn', category: 'fly', aliases: ['mickey finn streamer'] },
  { name: 'Black Ghost', category: 'fly', aliases: ['black ghost streamer'] },
  { name: 'Sparkler', category: 'fly', aliases: ['sparkler lure'] },
  { name: 'Sunras', category: 'fly', aliases: ['sunras lure'] },
  { name: 'Dancer', category: 'fly', aliases: ['dancer lure', 'sunra dancer'] },
  { name: 'Viva', category: 'fly', aliases: ['viva lure', 'black viva'] },
  { name: 'Tadpole', category: 'fly', aliases: ['tadpole fly', 'tadpole lure'] },
  { name: 'Minkie', category: 'fly', aliases: ['minkie lure', 'minkie streamer'] },
  { name: 'Cat Booby', category: 'fly', aliases: ['booby cat', 'cats whisker booby'] },
  { name: 'Booby', category: 'fly', aliases: ['booby fly', 'booby lure'] },
  { name: 'Cormorant Booby', category: 'fly', aliases: ['booby cormorant'] },
  { name: 'Cormorant Minkie', category: 'fly', aliases: ['cormorant minkie lure'] },
  { name: 'Olive Buzzard', category: 'fly', aliases: ['buzzard', 'olive buzzard'] },
  { name: 'Black Buzzard', category: 'fly', aliases: ['black buzzard lure'] },
  { name: 'Dahlberg Diver', category: 'fly', aliases: ['dahlberg'] },
  { name: 'Gurgler', category: 'fly', aliases: ['gurgler fly'] },
  { name: 'Foam Popper', category: 'fly', aliases: ['popper fly', 'foam popper fly'] },
  { name: 'Egg Fly', category: 'fly', aliases: ['egg', 'glow bug', 'beadhead egg'] },
  { name: 'Glo Bug', category: 'fly', aliases: ['glow bug fly'] },
  { name: 'Salmon Egg', category: 'fly', aliases: ['salmon egg fly'] },

  // Salmon flies
  { name: 'Allys Shrimp', category: 'fly', aliases: ['allys', 'ally shrimp'] },
  { name: 'T Cascade', category: 'fly', aliases: ['cascade', 'tcascade'] },
  { name: 'Willie Gunn', category: 'fly', aliases: ['willie gunn salmon'] },
  { name: 'Garry Dog', category: 'fly', aliases: ['garry'] },
  { name: 'Sunray Shadow', category: 'fly', aliases: ['sunray'] },
  { name: 'Silver Stoat', category: 'fly', aliases: ['stoat'] },
  { name: 'Hairy Mary', category: 'fly', aliases: ['hairy mary salmon'] },
  { name: 'Blue Charm', category: 'fly', aliases: ['blue charm salmon'] },
  { name: 'Park Shrimp', category: 'fly', aliases: ['park'] },
  { name: 'Gold Bodied Willie Gunn', category: 'fly', aliases: ['gold willie gunn'] },
  { name: 'Francis', category: 'fly', aliases: ['francis salmon fly'] },
  { name: 'Monkey', category: 'fly', aliases: ['monkey fly', 'snaelda'] },
  { name: 'Snaelda', category: 'fly', aliases: ['snaelda salmon'] },
  { name: 'Temple Dog', category: 'fly', aliases: ['temple dog salmon'] },
  { name: 'Flamethrower', category: 'fly', aliases: ['flamethrower salmon'] },
  { name: 'Yellow Flying Scamp', category: 'fly', aliases: ['flying scamp'] },
  { name: 'Crathie Fly', category: 'fly', aliases: ['crathie'] },
  { name: 'Garry Dog Tube', category: 'fly', aliases: ['garry dog tube fly'] },
  { name: 'Micro Tube', category: 'fly', aliases: ['micro tube fly'] },
  { name: 'Cone Head', category: 'fly', aliases: ['conehead salmon'] },

  // Sea trout flies
  { name: 'Bibio Sea Trout', category: 'fly', aliases: ['bibio sea trout'] },
  { name: 'Butcher Sea Trout', category: 'fly', aliases: ['butcher sea trout'] },
  { name: 'Medicine', category: 'fly', aliases: ['medicine fly', 'alexandra'] },
  { name: 'Teal & Silver', category: 'fly', aliases: ['teal silver sea trout'] },
  { name: 'Muddler Sea Trout', category: 'fly', aliases: ['muddler sea trout'] },

  // Stillwater / reservoir patterns
  { name: 'Apps Bloodworm', category: 'fly', aliases: ['apps bloodworm', 'apps'] },
  { name: 'FAB', category: 'fly', aliases: ['foam arsed blob', 'fab fly'] },
  { name: 'Fritz Buzzer', category: 'fly', aliases: ['fritz', 'fritz midge'] },
  { name: 'UV Olive', category: 'fly', aliases: ['uv olive nymph'] },
  { name: 'Hot Head Damsel', category: 'fly', aliases: ['hot head damsel'] },
  { name: 'Jiggy Bugger', category: 'fly', aliases: ['jiggy'] },
  { name: 'Dancing Damsel', category: 'fly', aliases: ['dancing damsel fly'] },
  { name: 'Mega Muddler', category: 'fly', aliases: ['mega muddler'] },
  { name: 'Humungus', category: 'fly', aliases: ['humungus lure'] },
  { name: 'Killer Shrimp', category: 'fly', aliases: ['killer shrimp fly'] },
  { name: 'Orange Blob', category: 'fly', aliases: ['orange blob lure'] },
  { name: 'Tequila Blob', category: 'fly', aliases: ['tequila'] },
  { name: 'Estaz Egg', category: 'fly', aliases: ['estaz'] },
  { name: 'Squirmy Worm', category: 'fly', aliases: ['squirmy worm fly'] },
  { name: 'Snake Fly', category: 'fly', aliases: ['snake', 'snake fly lure'] },
  { name: 'Wiggle Tail', category: 'fly', aliases: ['wiggle tail fly'] },
];

// ============================================================
// LURES — comprehensive UK popular lures
// ============================================================
export const LURES: BaitEntry[] = [
  { name: 'Mepps Aglia', category: 'lure', aliases: ['mepps', 'aglia', 'mepps aglia spinner'] },
  { name: 'Mepps Comet', category: 'lure', aliases: ['mepps comet spinner'] },
  { name: 'Mepps Longcast', category: 'lure', aliases: ['mepps longcast spinner'] },
  { name: 'Mepps Black Fury', category: 'lure', aliases: ['black fury', 'mepps black fury'] },
  { name: 'Abu Toby', category: 'lure', aliases: ['toby', 'abu toby spoon'] },
  { name: 'Abu Droppen', category: 'lure', aliases: ['droppen', 'abu droppen spoon'] },
  { name: 'Abu Hi-Lo', category: 'lure', aliases: ['hi-lo', 'hi lo'] },
  { name: 'Abu Toro', category: 'lure', aliases: ['toro', 'abu toro spoon'] },
  { name: 'Blue Fox Super Vibrax', category: 'lure', aliases: ['blue fox', 'vibrax', 'super vibrax'] },
  { name: 'Rooster Tail', category: 'lure', aliases: ['rooster tail spinner'] },
  { name: 'Panther Martin', category: 'lure', aliases: ['panther martin spinner'] },
  { name: 'Dexter Wedge', category: 'lure', aliases: ['dexter', 'wedge'] },
  { name: 'Sprat Spoon', category: 'lure', aliases: ['sprat', 'sprat spoon lure'] },
  { name: 'Salmo Spoon', category: 'lure', aliases: ['salmo', 'salmo spoon lure'] },
  { name: 'Trolling Spoon', category: 'lure', aliases: ['trolling spoon lure'] },
  { name: 'Rapala Original Floater', category: 'lure', aliases: ['rapala', 'original floater', 'rapala floater'] },
  { name: 'Rapala Jointed', category: 'lure', aliases: ['rapala jointed', 'jointed rapala'] },
  { name: 'Rapala X-Rap', category: 'lure', aliases: ['x-rap', 'xrap', 'rapala xrap'] },
  { name: 'Rapala Count Down', category: 'lure', aliases: ['countdown', 'rapala countdown', 'rapala cd'] },
  { name: 'Rapala Husky Jerk', category: 'lure', aliases: ['husky jerk', 'husky'] },
  { name: 'Rapala Shadow Rap', category: 'lure', aliases: ['shadow rap', 'shadow'] },
  { name: 'Rapala Scatter Rap', category: 'lure', aliases: ['scatter rap', 'scatter'] },
  { name: 'Heddon Super Spook', category: 'lure', aliases: ['super spook', 'heddon spook', 'spook'] },
  { name: 'Lucky Craft Pointer', category: 'lure', aliases: ['lucky craft', 'pointer', 'lucky pointer'] },
  { name: 'Yo-Zuri Crystal Minnow', category: 'lure', aliases: ['yo-zuri', 'crystal minnow', 'yo zuri'] },
  { name: 'Yo-Zuri Mag Minnow', category: 'lure', aliases: ['mag minnow'] },
  { name: 'Deep Diving Crank', category: 'lure', aliases: ['deep crank', 'deep diver', 'deep diving crankbait'] },
  { name: 'Shallow Crank', category: 'lure', aliases: ['shallow crankbait', 'shallow diver'] },
  { name: 'Lipless Crank', category: 'lure', aliases: ['lipless crankbait', 'rattle trap'] },
  { name: 'Square Bill', category: 'lure', aliases: ['square bill crankbait'] },
  { name: 'Rat-L-Trap', category: 'lure', aliases: ['rat l trap', 'rattle trap'] },
  { name: 'Bandit', category: 'lure', aliases: ['bandit crankbait'] },
  { name: 'Hard Jerkbait', category: 'lure', aliases: ['jerkbait', 'hard jerk'] },
  { name: 'Soft Jerkbait', category: 'lure', aliases: ['soft jerk', 'soft jerkbait'] },
  { name: 'Glide Bait', category: 'lure', aliases: ['glide', 'glider'] },
  { name: 'Berkley PowerBait Jerk Shad', category: 'lure', aliases: ['powerbait jerk shad', 'jerk shad'] },
  { name: 'Curly Tail Grub', category: 'lure', aliases: ['grub', 'curly tail', 'twintail grub'] },
  { name: 'Twintail', category: 'lure', aliases: ['twin tail', 'double tail grub'] },
  { name: 'Senko', category: 'lure', aliases: ['senko worm', 'gary yamamoto senko'] },
  { name: 'Ned Rig', category: 'lure', aliases: ['ned', 'ned rig jig'] },
  { name: 'Creature Bait', category: 'lure', aliases: ['creature', 'creature bait soft plastic'] },
  { name: 'Tube Bait', category: 'lure', aliases: ['tube', 'tube jig'] },
  { name: 'Swimbait Soft', category: 'lure', aliases: ['soft swimbait'] },
  { name: 'Bucktail Jig', category: 'lure', aliases: ['bucktail', 'bucktail jig lure'] },
  { name: 'Round Jighead', category: 'lure', aliases: ['jighead', 'round jig head'] },
  { name: 'Football Jig', category: 'lure', aliases: ['football jig head'] },
  { name: 'Swim Jig', category: 'lure', aliases: ['swim jig head'] },
  { name: 'Finesse Jig', category: 'lure', aliases: ['finesse jig head'] },
  { name: 'Ned Jig', category: 'lure', aliases: ['ned jig head'] },
  { name: 'Hard Swimbait', category: 'lure', aliases: ['hard swimbait'] },
  { name: 'Paddletail', category: 'lure', aliases: ['paddle tail', 'paddletail soft plastic'] },
  { name: 'Hollow Body Swimbait', category: 'lure', aliases: ['hollow body', 'hollow swimbait'] },
  { name: 'Multi-Joint Swimbait', category: 'lure', aliases: ['multi joint', 'jointed swimbait'] },
  { name: 'Popper', category: 'lure', aliases: ['popper lure', 'topwater popper'] },
  { name: 'Walker', category: 'lure', aliases: ['walking bait', 'walker lure'] },
  { name: 'Prop Bait', category: 'lure', aliases: ['prop', 'propeller bait'] },
  { name: 'Buzzbait', category: 'lure', aliases: ['buzz bait', 'buzzbait lure'] },
  { name: 'Frog Lure', category: 'lure', aliases: ['frog', 'hollow frog', 'topwater frog'] },
  { name: 'Stickbait', category: 'lure', aliases: ['stick bait', 'walk the dog'] },
  { name: 'Vibration Bait', category: 'lure', aliases: ['vib', 'vibration lure', 'rattling vib'] },
  { name: 'Rattling Vib', category: 'lure', aliases: ['rattle vib', 'rattling lure'] },
  { name: 'Spinnerbait', category: 'lure', aliases: ['spinner bait', 'safety pin spinner'] },
  { name: 'Chatterbait', category: 'lure', aliases: ['chatter bait', 'bladed jig'] },
  { name: 'Bladed Jig', category: 'lure', aliases: ['bladed swim jig'] },
  { name: 'Soft Plastic Shad', category: 'lure', aliases: ['shad soft plastic', 'shad imitation'] },
  { name: 'Soft Plastic Minnow', category: 'lure', aliases: ['minnow soft plastic'] },
  { name: 'Soft Plastic Lizard', category: 'lure', aliases: ['lizard soft plastic'] },
  { name: 'Soft Plastic Worm', category: 'lure', aliases: ['worm soft plastic', 'ribbon tail worm'] },
  { name: 'Drop Shot Worm', category: 'lure', aliases: ['drop shot', 'dropshot worm'] },
  { name: 'Ned Bait', category: 'lure', aliases: ['ned bait soft plastic'] },
  { name: 'Jigging Rap', category: 'lure', aliases: ['jigging rapala', 'jig rap'] },
  { name: 'Vertical Jig', category: 'lure', aliases: ['vertical jigging lure'] },
  { name: 'Slab Spoon', category: 'lure', aliases: ['slab', 'slab spoon lure'] },
  { name: 'Casting Spoon', category: 'lure', aliases: ['casting spoon lure'] },
  { name: 'Weedless Spoon', category: 'lure', aliases: ['weedless spoon lure'] },
  { name: 'Savage Gear Sandeel', category: 'lure', aliases: ['savage gear', 'sandeel lure', 'savage gear sandeel'] },
  { name: 'Savage Gear Rotex', category: 'lure', aliases: ['rotex', 'savage gear rotex'] },
  { name: 'Fiiish Black Minnow', category: 'lure', aliases: ['black minnow', 'fiiish', 'fiiish black minnow'] },
  { name: 'Duo Tide Minnow', category: 'lure', aliases: ['duo', 'tide minnow', 'duo tide minnow'] },
  { name: 'IMA Sasuke', category: 'lure', aliases: ['ima', 'sasuke', 'ima sasuke'] },
  { name: 'Megabass Vision 110', category: 'lure', aliases: ['megabass', 'vision 110', 'megabass vision'] },
  { name: 'Jackall Squad Minnow', category: 'lure', aliases: ['jackall', 'squad minnow'] },
  { name: 'Westin Swim', category: 'lure', aliases: ['westin', 'westin swim lure'] },
  { name: 'Daiwa Salt Pro Minnow', category: 'lure', aliases: ['daiwa', 'salt pro minnow', 'daiwa spm'] },
  { name: 'Tsunami Talkin Popper', category: 'lure', aliases: ['tsunami', 'talkin popper'] },
  { name: 'Gulp Sandworm', category: 'lure', aliases: ['gulp', 'gulp sandworm lure'] },
  { name: 'Berkley Gulp Minnow', category: 'lure', aliases: ['gulp minnow', 'berkley gulp'] },
  { name: 'Z-Man Finesse TRD', category: 'lure', aliases: ['z-man', 'finesse trd', 'zman trd'] },
  { name: 'Keitech Fat Swing Impact', category: 'lure', aliases: ['keitech', 'fat swing impact', 'keitech swing impact'] },
  { name: 'Keitech Easy Shiner', category: 'lure', aliases: ['easy shiner', 'keitech easy shiner'] },
  { name: 'Manns Jelly Worm', category: 'lure', aliases: ['manns', 'jelly worm', 'manns jelly worm'] },
  { name: 'Gummi Minnow', category: 'lure', aliases: ['gummi', 'gummi minnow soft plastic'] },
];

// ============================================================
// BAITS — standard coarse and sea baits
// ============================================================
export const BAITS: BaitEntry[] = [
  { name: 'Maggot', category: 'bait', aliases: ['maggots', 'squatt', 'pinkie', 'gentles'] },
  { name: 'Worm', category: 'bait', aliases: ['lobworm', 'dendrobaena', 'redworm', 'brandling'] },
  { name: 'Boilie', category: 'bait', aliases: ['boilies', 'bottom bait', 'pop-up boilie'] },
  { name: 'Pellet', category: 'bait', aliases: ['halibut pellet', 'expander pellet', 'micro pellet'] },
  { name: 'Sweetcorn', category: 'bait', aliases: ['corn', 'maize'] },
  { name: 'Bread', category: 'bait', aliases: ['bread flake', 'bread punch', 'crust', 'bread crust'] },
  { name: 'Luncheon Meat', category: 'bait', aliases: ['spam', 'meat', 'tinned meat'] },
  { name: 'Casters', category: 'bait', aliases: ['caster', 'maggot caster'] },
  { name: 'Hemp', category: 'bait', aliases: ['hempseed', 'hemp seed'] },
  { name: 'Tares', category: 'bait', aliases: ['tare'] },
  { name: 'Deadbait', category: 'bait', aliases: ['dead bait', 'dead fish bait', 'deadbait roach'] },
  { name: 'Livebait', category: 'bait', aliases: ['live bait', 'live fish', 'livebait roach'] },
  { name: 'Prawn', category: 'bait', aliases: ['shrimp bait', 'prawn bait'] },
  { name: 'Squid Bait', category: 'bait', aliases: ['squid strip', 'squid', 'squid tentacle'] },
  { name: 'Ragworm', category: 'bait', aliases: ['rag worm', 'king rag', 'ragworm bait'] },
  { name: 'Lugworm', category: 'bait', aliases: ['lug worm', 'black lug', 'blow lug'] },
  { name: 'Crab Bait', category: 'bait', aliases: ['peeler crab', 'soft crab', 'crab', 'hermit crab'] },
  { name: 'Mussel', category: 'bait', aliases: ['mussels', 'mussel bait'] },
  { name: 'Sand Eel Bait', category: 'bait', aliases: ['sand eel', 'sandeel bait'] },
  { name: 'Mackerel Strip', category: 'bait', aliases: ['mackerel bait', 'fish strip', 'mackerel fillet'] },
  { name: 'Paste', category: 'bait', aliases: ['trout paste', 'cheese paste', 'paste bait'] },
  { name: 'Cheese', category: 'bait', aliases: ['cheese bait'] },
  { name: 'Particles', category: 'bait', aliases: ['maize', 'chickpeas', 'tiger nuts', 'hempseed mix'] },
  { name: 'Fake Bait', category: 'bait', aliases: ['plastic corn', 'fake corn', 'artificial bait'] },
  { name: 'Hemp & Tares', category: 'bait', aliases: ['hemp and tares'] },
  { name: 'Worm & Caster', category: 'bait', aliases: ['worm and caster', 'worm caster'] },
  { name: 'Maggot & Caster', category: 'bait', aliases: ['maggot and caster'] },
  { name: 'Peanuts', category: 'bait', aliases: ['peanut', 'monkey nut'] },
  { name: 'Tigernuts', category: 'bait', aliases: ['tiger nut', 'tigernut'] },
  { name: 'Maple Peas', category: 'bait', aliases: ['maple pea'] },
  { name: 'Wheat', category: 'bait', aliases: ['wheat bait'] },
  { name: 'Perlon', category: 'bait', aliases: ['perlon bait'] },
  { name: 'Squid & Octopus', category: 'bait', aliases: ['squid octopus cocktail'] },
  { name: 'Black Lug Cocktail', category: 'bait', aliases: ['lug and squid', 'lug squid'] },
  { name: 'Mussel & Lug', category: 'bait', aliases: ['mussel lug cocktail'] },
  { name: 'Fish Gut', category: 'bait', aliases: ['fish guts', 'gut bait'] },
  { name: 'Clam', category: 'bait', aliases: ['clam bait', 'razor clam'] },
  { name: 'Razor Clam', category: 'bait', aliases: ['razorfish', 'razor clam bait'] },
  { name: 'Cockle', category: 'bait', aliases: ['cockle bait'] },
  { name: 'Limpet', category: 'bait', aliases: ['limpet bait'] },
  { name: 'Winkles', category: 'bait', aliases: ['winkle', 'periwinkle'] },
  { name: 'Sprat', category: 'bait', aliases: ['sprat bait', 'sprat deadbait'] },
  { name: 'Herring', category: 'bait', aliases: ['herring bait', 'herring deadbait'] },
  { name: 'Smelt Bait', category: 'bait', aliases: ['smelt deadbait'] },
  { name: 'Roach Deadbait', category: 'bait', aliases: ['roach deadbait'] },
  { name: 'Bleak Deadbait', category: 'bait', aliases: ['bleak deadbait'] },
  { name: 'Dace Deadbait', category: 'bait', aliases: ['dace deadbait'] },
];

// ============================================================
// ALL BAITS combined
// ============================================================
export const ALL_BAITS: BaitEntry[] = [...FLIES, ...LURES, ...BAITS];

// Search function for autocomplete
export function searchBaits(query: string, category?: BaitEntry['category'], limit = 20): BaitEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) {
    const pool = category ? ALL_BAITS.filter((b) => b.category === category) : ALL_BAITS;
    return pool.slice(0, limit);
  }
  const pool = category ? ALL_BAITS.filter((b) => b.category === category) : ALL_BAITS;
  return pool
    .filter((b) => {
      if (b.name.toLowerCase().includes(q)) return true;
      if (b.aliases?.some((a) => a.toLowerCase().includes(q))) return true;
      return false;
    })
    .slice(0, limit);
}

// Get category for a given bait name
export function getBaitCategory(name: string): BaitEntry['category'] | null {
  if (!name) return null;
  const lower = name.toLowerCase();
  const entry = ALL_BAITS.find(
    (b) => b.name.toLowerCase() === lower ||
    b.aliases?.some((a) => a.toLowerCase() === lower)
  );
  return entry?.category ?? null;
}
